### ISSUE TITLE
Extracting gemstones or using Weapon Lapisia or Armor Lapisia, will not use Lucky Charm

### ISSUE THREAD

**Issue by gaobbcdd** [kurtekat/shaiya-episode-6#100]
Extracting gemstones or using Weapon Lapisia or Armor Lapisia, will not use Lucky Charm。
Only used Lucky Charm when combining gemstones
![image](https://github.com/kurtekat/shaiya-episode-6/assets/66864390/d3720690-6166-4b18-bdbe-b40553854744)

Dear developer, thank you for your significant contribution to shaiya

**Comment by kurtekat** [comment]
Are you requesting a feature? As far as I know, lucky charms have always worked in the way you're describing.

**Comment by kurtekat** [comment]
I'm pretty sure they have nothing to do with upgrading as well. If ep6 added some kind of item for this, let me know. Otherwise, I'm not going to get into it.

**Comment by gaobbcdd** [comment]
Sorry. I'm not sure if ep6 protects against extraction either.

**Comment by kurtekat** [comment]
No need to apologize.

**Comment by Spelunkern** [comment]
Lucky charms have never protected items from breaking at extraction, it's not something of EP6.

Besides that, there is an item on EP6 specifically designed for Lapisia protection:

- 'Special Lucky Charm' ,  ID  101 132, Effect 103.

**Comment by gaobbcdd** [comment]
thank you .Although I raised questions, I am not very familiar with EP6 either

**Comment by kurtekat** [comment]
I've been learning about it as I go this whole time. :P It's cool.

**Comment by kurtekat** [comment]
They added a boolean to the 0x805 packet to indicate whether the user has the 101132 charm. This feature may be doable.

**Comment by kurtekat** [comment]
https://github.com/kurtekat/shaiya-episode-6/commit/6d093f5ee72db2008a3399a7246821bce7c48fb5

I ain't got a lot to work with, as far as incoming packet data is concerned. I think the item does what it's supposed to do, based on the description. It seems to work as expected in every scenario.

**Comment by gaobbcdd** [comment]
Great, that's great.

**Comment by kurtekat** [comment]
Did you try it?

**Comment by kurtekat** [comment]
Have you tried it?

**Comment by Spelunkern** [comment]
Tested, it doesn't work as expected.
The item it's not consumed at use, albeit the interface to ask for the lucky charm appears.
Also, the item get broken anyways.

**Comment by kurtekat** [comment]
That's the exact opposite of my tests xD

**Comment by kurtekat** [comment]
You have the SHAIYA_EP6_BLACKSMITH macro enabled?

**Comment by Spelunkern** [comment]
Yeah thats the problem, im testing right now without that macro exposed, should work

**Comment by Spelunkern** [comment]
Another reason to remove the blacksmith version XD

**Comment by kurtekat** [comment]
I'm removing that macro. I don't care about people's CTs anymore.

**Comment by Spelunkern** [comment]
It's the best option for the project ;)

**Comment by kurtekat** [comment]
Sure. So, does this feature work or not? If there's an issue, I'm just gonna remove it, because that damn client packet doesn't give me anything to work with except a boolean. No bag, not slot, no nothing. I almost didn't do it at all because of that.

**Comment by Spelunkern** [comment]
It works, sorry for the missunderstanding.

**Comment by kurtekat** [comment]
You don't have to apologize.

**Comment by kurtekat** [comment]
Do you know of any other official item with the 103 effect?

**Comment by kurtekat** [comment]
I see 101 90

**Comment by Spelunkern** [comment]
Just 101 90,  which it's a copy of the 101 132 but tradeable.

**Comment by kurtekat** [comment]
ok. i need some time to think about this.

**Comment by Spelunkern** [comment]
Personally i don't think you need to add both, just keep the way it is.

**Comment by kurtekat** [comment]
If there's a way I can, I will. I just need to check the packet one more time.

**Comment by kurtekat** [comment]
I thought the last field is the npcId (added in 6.4), but it may actually be the itemId. I need to make sure.

**Comment by Spelunkern** [comment]
Btw since finally the blacksmith version it's being removed for good, i think eventually we should add custom runes support on the main project to keep the feature possible.

**Comment by Spelunkern** [comment]
A side note on that last point:
The custom runes are actually an EP6 feature, servers use them a bit different but the same function after all.
OS offered two runes:  Random ones and OJ doublers (Get double stats of max recreation possible)
Servers get rid of the OJ doubles and usually makes removal and perfect runes among the random ones.

**Comment by kurtekat** [comment]
Send specs via email. I'm locking this as resolved.

**Comment by kurtekat** [comment]
I pushed a fix for this yesterday. Sometimes, it wasn't consuming the charm on success. I moved the detour to another address.
