### ISSUE TITLE
(Suggestion)  A few fixes for the PS_Game

### ISSUE THREAD

**Issue by Spelunkern** [kurtekat/shaiya-episode-6#101]
Just a few modifications for common fixes and/or enchancements of the ps_game.

**Helmet/Cloak drop fix:**
004BAFC8:
db 90 90 90 90 90 90 90 90 90

004BAFD1:
db 90 90 90 90 90 90 90 90 90

00473BBD:
db 90 90 90 90 90 90 90 90 90 90 90 90 90

**Global Auction House:**
004862DE :
NOP

**Mounts with Stats support**
0046861E:
mov byte ptr [esp+13],00

**EP6 like mount casting time**
00477147:
add esi,#100

0047714F:
add esi,#100

A side comment:
It seems the Ps_Game without the Item Duration effect have been removed, i suggest if it can be re-added since most people never use the feature ;)

**Comment by kurtekat** [comment]
People need to add those mods with CTs. The badge/mantle issue was an exception. Is there a reason why they can't use the ps_game, even if they don't want item duration? What exactly is the problem?

**Comment by Spelunkern** [comment]
The reason is you need to use a very specific and niche way to edit your data with the item duration support, otherwise ps-game instant crashes. Basically it makes things very annoying for a feature that very few people uses, thats the reason of why i suggest also leaving the option to skip using it.

**Comment by Spelunkern** [comment]
Besides the item duration suggestion, all modifications for the ps-game are included on essentials, people don't need scripts. I only suggest to add them since they are part of ep6 usual behavior, but it's ok

**Comment by kurtekat** [comment]
Ok.

**Comment by kurtekat** [comment]
I'm not adding a macro if I can help it. They can comment it out here:

```cpp
// main.cpp
//hook::item_duration();
```

Those time fields have to be in the packet either way. If they use the ps_game I just added, the `duration` field should always equal to zero, which will keep time values from being added to the packets.

**Comment by Spelunkern** [comment]
Thank you, it's more than enough
