### ISSUE TITLE
Item Mall -> Send Gift crash

### ISSUE THREAD

**Issue by xareI** [kurtekat/shaiya-episode-6#102]
In itemmall, when im choose a any free (0 AP) item, after that sending that item to anyone as a gift ps_game crashed.

**Comment by kurtekat** [comment]
I'll check it out.

**Comment by kurtekat** [comment]
I got nothing. I tried at least a dozen times. Are you injecting any CTs related to the item mall?

**Comment by kurtekat** [comment]
Here's all the addresses to check. If there's anything else being injected at or around these addresses, you should be able to see it. It will help a lot to have sdev.pdb in the directory.

```
// ep5 and ep6.4
0x47A4A4
0x48876F
0x488A80
0x47D525

// ep6.4
0x4886E0
0x488CC9
0x464B5A
```

**Comment by kurtekat** [comment]
if i don't hear back from you by the end of the hour, i'm gonna close this issue.

**Comment by kurtekat** [comment]
> Here its crash info.
> 
> Minidump write end.....................
> 
> 0x77596122 KERNELBASE.dll: RaiseException + 98
> 
> 0x73A4D9F2 sdev.dll: _CxxThrowException + 102 D:\a_work\1\s\src\vctools\crt\vcruntime\src\eh\throw.cpp, Line 81 + 25
> 
> 0x73A49F11 sdev.dll: std::_XGetLastError + 58 D:\a_work\1\s\src\vctools\crt\github\stl\src\xonce.cpp, Line 42 + 28
> 
> 0x73A34283 sdev.dll: std::chrono::_Tzdb_generate_time_zones + 611 C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include\chrono, Line 2105
> 
> 0x73A33548 sdev.dll: std::chrono::tzdb_list::tzdb_list + 88 C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include\chrono, Line 2280 + 12
> 
> 0x73A3463D sdev.dll: std::chrono::get_tzdb_list + 93 C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include\chrono, Line 2338
> 
> 0x73A346EE sdev.dll: shaiya::ServerTime::now + 14 D:\ShaiyaEP6\Kaynaklar\shaiya-episode-6-main\sdev\include\shaiya\src\ServerTime.cpp, Line 48 + 5
> 
> 0x73A476FA sdev.dll: packet_shop::send_purchase3 + 26 D:\ShaiyaEP6\Kaynaklar\shaiya-episode-6-main\sdev\src\packet_shop.cpp, Line 87 + 5
> 
> 0x73A4748F sdev.dll: naked_0x488A80 + 31 D:\ShaiyaEP6\Kaynaklar\shaiya-episode-6-main\sdev\src\packet_shop.cpp, Line 163
> 
> Stack trace end.....................
> 
> Minidump write end.....................
> 
> 0x77596122 KERNELBASE.dll: RaiseException + 98
> 
> 0x73A4D9F2 sdev.dll: _CxxThrowException + 102 D:\a_work\1\s\src\vctools\crt\vcruntime\src\eh\throw.cpp, Line 81 + 25
> 
> 0x73A49F11 sdev.dll: std::_XGetLastError + 58 D:\a_work\1\s\src\vctools\crt\github\stl\src\xonce.cpp, Line 42 + 28
> 
> 0x73A34283 sdev.dll: std::chrono::_Tzdb_generate_time_zones + 611 C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include\chrono, Line 2105
> 
> 0x73A33548 sdev.dll: std::chrono::tzdb_list::tzdb_list + 88 C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include\chrono, Line 2280 + 12
> 
> 0x73A3463D sdev.dll: std::chrono::get_tzdb_list + 93 C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include\chrono, Line 2338
> 
> 0x73A346EE sdev.dll: shaiya::ServerTime::now + 14 D:\ShaiyaEP6\Kaynaklar\shaiya-episode-6-main\sdev\include\shaiya\src\ServerTime.cpp, Line 48 + 5
> 
> 0x73A476FA sdev.dll: packet_shop::send_purchase3 + 26 D:\ShaiyaEP6\Kaynaklar\shaiya-episode-6-main\sdev\src\packet_shop.cpp, Line 87 + 5
> 
> 0x73A4748F sdev.dll: naked_0x488A80 + 31 D:\ShaiyaEP6\Kaynaklar\shaiya-episode-6-main\sdev\src\packet_shop.cpp, Line 163
> 
> Stack trace end.....................
> 
> Stack trace(all thread) begin.....................

**Comment by kurtekat** [comment]
@xareI 

When's the last time you cloned the repository? I think I patched this already.

**Comment by kurtekat** [comment]
![Capture](https://github.com/kurtekat/shaiya-episode-6/assets/142125482/4e88c02e-c62c-48b6-89e5-d1bcf79ec4db)

I have a debugger attached. Everything looks ok. I patched those time functions twice in the last few days or so. Your dump looks like it may be the code from the first patch.

**Comment by kurtekat** [comment]
@xareI please answer my question or upload `ServerTime.h` and `ServerTime.cpp` from the bugged project.

https://github.com/kurtekat/shaiya-episode-6/issues/102#issuecomment-2198328028

**Comment by xareI** [comment]
Yeah not updated, it fixed thanks for reply.

**Comment by kurtekat** [comment]
Cool. You're welcome.
