### ISSUE TITLE
Titles not working.

### ISSUE THREAD

**Issue by xareI** [kurtekat/shaiya-episode-6#107]
I did check several times and 
```
            user->title.text = CStaticText::Create(text);
            auto w = CStaticText::GetTextWidth(text);
            user->title.pointX = long(w * 0.5);
```
            not working rendering to string 
            eax is null after sending function

**Comment by kurtekat** [comment]
![Capture](https://github.com/user-attachments/assets/7453e198-2486-482d-bd2e-485270ac5379)

Ok. If that snip is all you're going to provide, I'm gonna to close this issue. I already closed the duplicate.

**Comment by xareI** [comment]
Did u test with non-guild ?

**Comment by xareI** [comment]
i did test with non-guild and let me test with guild names

**Comment by kurtekat** [comment]
> Did u test with non-guild ?

Yes,

**Comment by xareI** [comment]
Is there a possible if eft file not in shaiya data file, if render is fail not show/rendering titles ?
cz i don't have eft files tbh if its possible to upload bin of sdev-client/bin/ folder.

**Comment by kurtekat** [comment]
The text shouldn't fail if the .eft is missing. Here's the .eft from my client.

[Character_Effect_01.zip](https://github.com/user-attachments/files/16190537/Character_Effect_01.zip)

**Comment by kurtekat** [comment]
Do you have itemId 120043 equipped?

![Capture3](https://github.com/user-attachments/assets/33a7077b-ee04-40f1-b8c8-b0c91080a58c)

**Comment by xareI** [comment]
Yeah ofc,
[https://img001.prntscr.com/file/img001/iEuq98_KQgScTLJ3kkBg1A.png](url)

**Comment by xareI** [comment]
[https://img001.prntscr.com/file/img001/BkS6LdsaTEK_s8ZzHhXqCQ.png](url)

**Comment by kurtekat** [comment]
![Capture2](https://github.com/user-attachments/assets/08a010bc-194f-4565-a2c5-a55397d25c89)

You want to upload that game.exe here so I can look at it? I don't know what else I can do.

**Comment by kurtekat** [comment]
Or, let me see the code at this address: 0x57C280

**Comment by xareI** [comment]
https://drive.google.com/file/d/1z5qBtbT6snVKWsagpH6s8vauiSVJRDq6/view?usp=sharing

**Comment by kurtekat** [comment]
![Capture4](https://github.com/user-attachments/assets/8657aa74-d817-4407-a858-e5a64a3c0853)

Google is becoming a pain in the nuts. xD

https://wetransfer.com/

Send it to my email address. It's free. You don't have to create an account.

**Comment by xareI** [comment]
[https://prnt.sc/bXHzhY7T2aus](url)

**Comment by kurtekat** [comment]
Same as mine. I don't know what the problem could be.

**Comment by kurtekat** [comment]
![Capture2](https://github.com/user-attachments/assets/b2022ee2-1c41-40cf-aff9-61d81ecc3a39)

will you follow `CStaticText::Create and let me see the machine code?
