### ISSUE TITLE
Death Type Debuff not work

### ISSUE THREAD

**Issue by xareI** [kurtekat/shaiya-episode-6#108]
Death (filte) type of debuffs not working, while buff expired / removed it is have to be push to die toon.
But not dying.

[https://prnt.sc/Pgwksqylcinn](url)

**Comment by kurtekat** [comment]
![Shaiya0005](https://github.com/user-attachments/assets/4266c8d7-d0c5-44fa-a1d3-f8861b3dc544)
Mine works just fine.
