### ISSUE TITLE
Can you give an example of how to add more titles?

### ISSUE THREAD

**Issue by Sagwa094** [kurtekat/shaiya-episode-6#109]
Can you give an example of how to add more titles?

**Comment by kurtekat** [comment]
No.

**Comment by kurtekat** [comment]
Maybe I should say more. All you have to do is add the logic to the existing function. Technically, there's a packet for this stuff, but I don't want to try to implement it. It's not worth the trouble.

https://github.com/tristonplummer/Eden/blob/master/eden/common/include/shaiya/common/net/packet/game/CharacterOverlay.hpp
