### ISSUE TITLE
problems found

### ISSUE THREAD

**Issue by Sagwa094** [kurtekat/shaiya-episode-6#110]
I have two problems, items that should not last have a duration and the title effect does not appear and I have already checked and have it in the client.

![Shaiya0034](https://github.com/user-attachments/assets/29b58cb1-5583-49fb-8782-2ace12b14155)

**Comment by Sagwa094** [comment]
![Shaiya0034](https://github.com/user-attachments/assets/29b58cb1-5583-49fb-8782-2ace12b14155)

**Comment by kurtekat** [comment]
![Shaiya0004](https://github.com/user-attachments/assets/442b6f06-33d7-4b3e-a46f-9c54ef596084)

My item looks correct. Client-side, make sure the `Duration` and `ExtDuration` fields of that item are zero.

**Comment by kurtekat** [comment]
As far as I know, if `ExtDuration` is 0, that text will not appear in the item description.

**Comment by kurtekat** [comment]
Regarding the title effect, I had to add a sequence entry to the file. I tried one from two clients and neither of them worked.

[Character_Effect_01.zip](https://github.com/user-attachments/files/16229841/Character_Effect_01.zip)
