### ISSUE TITLE
Stat problem

### ISSUE THREAD

**Issue by Spotin2** [kurtekat/shaiya-episode-6#112]
So there seems to be an issue with stats.

The issue lays mainly in HP where it's different if I stat reset and if I relog.
Also there is something weird with the rest of the stats where you get negative stats, but I haven't managed to reproduce it as it's very random.

1. This picture is when I have used stat reset stone
![image](https://github.com/user-attachments/assets/3b15059e-b474-4686-bf85-3f90bb8783b7)

2. This picture is when I first login
![image](https://github.com/user-attachments/assets/aa4a75e4-3389-4431-8f10-347d2d5a7b83)

3. Negative stats
![image](https://github.com/user-attachments/assets/702667b8-0568-4f40-b282-db589fb9a86c)

**Comment by kurtekat** [comment]
I had a similar issue with Synergy at one time, but it was fixed (as far as I know). If you're using CTs or other libraries, please see if my detour is being overwritten or bypassed at the following address:

```cpp
// CUser::StatResetStatus
util::detour((void*)0x48F9BE, naked_0x48F9BE, 7);
```

I'll check it out in a little while.
