### ISSUE TITLE
PacketGem GetEnchantItem enchant value problem

### ISSUE THREAD

**Issue by xareI** [kurtekat/shaiya-episode-6#116]
auto enchantStep = CItem::GetEnchantStep(item);
This function not complete i think cz, gears starting enchanting 50+ enchant value you can see craftname values at end.

Weapon enchant are fine starting from 0.

i did fix on packet gem cpp line of lapisia

        auto max_enchant_step = 20;

        auto enchantStep = CItem::GetEnchantStep(item);

        if (enchantStep > 50) { //for lapisia gear
            max_enchant_step = 70;
            enchantStep = enchantStep - 50;
        }

        if (enchantStep == 50) {
            enchantStep = 0;
        }

**Comment by kurtekat** [comment]
Will you give me a step by step example of what I can do to see what you're talking about?

**Comment by xareI** [comment]
Weapon and Gears enchanted item value is different.
Weapon Step starting at 1. 1-20
Gears Step starting at 51-70.
Armor +7 = 57
Weapon +7 = 7
You can check adress value from getting auto enchantStep = CItem::GetEnchantStep(item);

**Comment by kurtekat** [comment]
That's not what I asked for. It's fine. I'm just gonna block you. I'll fix this when I have time.

**Comment by kurtekat** [comment]
https://github.com/kurtekat/shaiya-episode-6/commit/53dacfa4c20cac0a93c9b53f389b23a91ac7c8d5
