### ISSUE TITLE
Distribute in Random Order

### ISSUE THREAD

**Issue by Spotin2** [kurtekat/shaiya-episode-6#117]
Is there a possible fix on Distribute in Random order? Where basically if 1 character in the raid (and is meant to received the drop) the items go in the floor instead of assigning it to another member in the raid?

You can test this with 2 members and change distribute to random order, then move one character to another map and you’ll see the results.

**Comment by kurtekat** [comment]
For random order, this is where it checks if the user is in range:

```
ps_game.exe+BB27F - mov eax,[esp+18]
// eax: killer
ps_game.exe+BB283 - mov ecx,esi
// ecx: user (supposed to get the drop)
// edi: monster
ps_game.exe+BB285 - call ps_game.exe+BAED0 // CMob::EnableApplyRangeItem
ps_game.exe+BB28A - test al,al
// if false, the item drops to the ground
ps_game.exe+BB28C - je ps_game.exe+BB434
```

You can look at that `CMob` method to see what it does. In my opinion, if that method returns `false`, you should try to randomly choose someone else and only make it jump to the original code if all else fails.
