### ISSUE TITLE
HP Bug and Cheat engine problems

### ISSUE THREAD

**Issue by Spelunkern** [kurtekat/shaiya-episode-6#60]
Hey, im leaving here the bugs/error most people have found on the files.

The first error already noticed and reported it's the ps_game being completely unable to load the sdev dll, a lot of things have been tried without success:
- Reinstalling microsoft c++ redistributables.
- Use a different version of cheat engine.
- Recompile the file to check if there is an error on the file.
Note that there is not an specific error to check, just the cheat engine it's unable to turn on the script to load the dll.

The second error for the server files it's the HP bug:
After a few hits the HP of the opposite players get bugged and drop to zero (Just a visually issue).
I leave a video here to show what happens in combat (It is not mine, but for a tester on the discord):
https://youtu.be/zyaeTQkGFHc

While i can run the files without problems, most people actually can't (Not just for lacking compiling knowledge, but for being unable to load the script). 
Thank you for your time.

**Comment by kurtekat** [comment]
i've spent the last hour trying to reproduce this hp issue and it's not happening. more than likely, there are important details that aren't being included. someone else checked it too and came to the same conclusion.

as far as injection goes, i'm not uploading files with `LoadLibrary` calls to work around this issue. it's not a problem with the project. it is configured to statically link the vc runtime. there's nothing else i can do about it.

as you know, there are many other ways to go about injecting the libraries. if they can't make it work, it's probably for the best. i know that sounds cold, but i can't do anything to help people when i don't have access to their machine.

**Comment by Spelunkern** [comment]
Thanks for the response.
I have doed my test on the error and i can confirm this:
* The error can happen if you use one or another game.exe, this does not happens on EP5 game.exe
* On the other hand, the error it's present on every (Or almost every) EP6 avaliable game.exe
Since the server files are EP5 with additions, i think the problem it's a client issue because the offsets of HP/HP bar are different from EP5 to EP6.

This could have two solutions:
- Modify the game.exe at the right offset to have EP5 parameters, which is hard because there is not info on working around the hp bug issue.
- Modify the ps_game to have HP/HP bar features of EP6.

I have tested with **every**  ps_game avaliable for EP6 and the error happens (Im using the latest sdev version, the 1.1.0.3).
Again, thank you for your time.

**Comment by kurtekat** [comment]
will you upload the game.exe you were using when you experienced this bug so i can reproduce it?

**Comment by Spelunkern** [comment]
[Game.zip](https://github.com/kurtekat/shaiya-episode-6/files/13358655/Game.zip)

**Comment by kurtekat** [comment]
try this one, without an CT files injected, please.
https://github.com/kurtekat/shaiya-episode-6/tree/main/client/0x16021200/sdev/bin

**Comment by Spelunkern** [comment]
Tested without modying or adding anything to the game, the bug still persist.
I attach an screnshoot showing the bug.
![Sin título](https://github.com/kurtekat/shaiya-episode-6/assets/150851205/166d676c-fb82-47ae-b4be-60f54ed7146a)

**Comment by kurtekat** [comment]
level 80... interesting.

**Comment by Spelunkern** [comment]
I checked with all levels, it is not a level issue (Yes it was the first thing that comes to my mind)

**Comment by Spelunkern** [comment]
![1](https://github.com/kurtekat/shaiya-episode-6/assets/150851205/4ec64df9-6f31-41de-9e1a-26ab3e2c2228)
With level 30 (for a example)  (Using the game.exe you suggest)

**Comment by kurtekat** [comment]
something isn't adding up here. please send me the ps_game you're using.

**Comment by Spelunkern** [comment]
[ps_game.zip](https://github.com/kurtekat/shaiya-episode-6/files/13358915/ps_game.zip)
Im using the ps game suggested by the github project (EP5 without modifications)

**Comment by kurtekat** [comment]
that's the file from the v2 directory. thanks for confirming. i had to make sure it wasn't modified at some point.

**Comment by Spelunkern** [comment]
Yes, im using the v2 ps_game

**Comment by kurtekat** [comment]
does this one display the bug too?
https://github.com/kurtekat/shaiya-episode-6/tree/main/client/0x16012100/sdev/bin

i'm not being random here, just so you know. i'm just trying to figure out if you see what i see.

**Comment by Spelunkern** [comment]
![1](https://github.com/kurtekat/shaiya-episode-6/assets/150851205/c8dbcbcc-1c1c-42b8-9d7d-c988b44eb8d6)
This one works without the issue

**Comment by kurtekat** [comment]
ok, now everything makes sense. everyone in my circle is using this one. i meant to send you this one the first time, so that's my bad. the first one i sent is the same build as the one you sent me, so that explains a lot. hopefully, i can take care of this without bugging the other one.

**Comment by Spelunkern** [comment]
Thank you for the help and time

**Comment by kurtekat** [comment]
[Game.zip](https://github.com/kurtekat/shaiya-episode-6/files/13359655/Game.zip)
this is a copy of the one you sent me. if it's fixed, please tell me and i'll share the difference i found in the two files.

**Comment by Spelunkern** [comment]
Tested, the bug unfortunately still persist

**Comment by kurtekat** [comment]
looks like the changes i made didn't save to the file for some reason. i'm gonna send another shortly.

**Comment by kurtekat** [comment]
ok, so this is the one i was gonna upload to my repo, so please try it without any dlls. this is the last one i'll send tonight.
[game_2.zip](https://github.com/kurtekat/shaiya-episode-6/files/13360570/game_2.zip)

**Comment by Spelunkern** [comment]
Hey, thanks for the help.
I have tested with your game.exe and works without problems. Im not sure if changing the adresses work for every ep6 game, but there is few reasons to not use your game.exe anyways.

I have maded a few QoL modifications for the game.exe you give to me:
- Minimap for dungeons enabled.
- IM freeze removed (Aka IM cut fix).
- Fast transition
Besides the small changes, i haven't added any dll to the file, remains clear.

Thank you!
[game.zip](https://github.com/kurtekat/shaiya-episode-6/files/13367202/game.zip)

**Comment by kurtekat** [comment]
good. i'm glad this is solved.

**Comment by kurtekat** [comment]
here's some more information about the cheat engine situation for people that are interested.

https://www.cheatengine.org/forum/viewtopic.php?t=620490
#55

**Comment by kurtekat** [comment]
To future readers:

https://github.com/kurtekat/shaiya-episode-6#recovery
