### ISSUE TITLE
I HAVE A GOOD IDEA ,Synergy Can use ini format files。This will be more convenient for editing

### ISSUE THREAD

**Issue by gaobbcdd** [kurtekat/shaiya-episode-6#63]
files name：setitem.ini
for example：
[SetItem_4_Effect_2]	
STR =0
DEX =0
REC =0
INT =0
WIS =0
LUC =20
	
[SetItem_4_Effect_4]	
STR =0
DEX =50
REC =0
INT =0
WIS =0
LUC =20
	
[SetItem_4_Effect_5]	
STR =70
DEX =50
REC =0
INT =0
WIS =0
LUC =20
	
[Setitem_5_Effect_2]	
STR =0
DEX =0
REC =0
INT =0
WIS =0
LUC =20
	
[Setitem_5_Effect_4]	
STR =50
DEX =0
REC =0
INT =0
WIS =0
LUC =20
	
[Setitem_5_Effect_5]	
STR =50
DEX =0
REC =70
INT =0
WIS =0
LUC =20
	
[Setitem_6_Effect_2]	
STR =	20
DEX =	0
REC =	0
INT =	0
WIS =	0
LUC =	0
	
[Setitem_6_Effect_4]	
STR =	20
DEX =	0
REC =	0
INT =	0
WIS =	0
LUC =	50
	
[Setitem_6_Effect_5]	
STR =	20
DEX =	70
REC =	0
INT =	0
WIS =	0
LUC =	50

**Comment by gaobbcdd** [comment]
ok, Forgive my shallow knowledge,

**Comment by kurtekat** [comment]
> ok, Forgive my shallow knowledge,

you don't have to ask forgiveness. we're all learning as we go.

**Comment by kurtekat** [comment]
you're ok. we're all learning as we go.
