### ISSUE TITLE
modify game.exe font

### ISSUE THREAD

**Issue by jason8995** [kurtekat/shaiya-episode-6#65]
Hi bowie，Could you please tell me how to modify game.exe font to support  Non-english client ? bcz when i use  game.exe with Non-english client，display of text is small and ugly，I‘m a rookie，appreciate for your excellent job ^^

**Comment by kurtekat** [comment]
i guess. you mind uploading the file here?

**Comment by kurtekat** [comment]
here's some reading material if you really want to learn how the game works.

[CreateFontA](https://learn.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-createfonta)
[LPD3DXFONT](https://learn.microsoft.com/en-us/windows/win32/direct3d9/id3dxfont)

this is where you can change the height the font after it's created.

```
00576D4D  6A 0D          PUSH 0D
```

try this, and let me know if it looks better. i changed it from 13 to 14. i think this is enough, but if it's not, 15 should certainly be enough.

[game_font-height-14.zip](https://github.com/kurtekat/shaiya-episode-6/files/13639856/game_font-height-14.zip)

**Comment by jason8995** [comment]
Hi Bowie，much much better using your modified game.exe，it's still not changed somewhere，but you have told me the way，I will spend time on how the game works and modify it on my own，I‘m a beginner，just love this game and have a lot memory of it，appreciate for your time and help，have a good day^^
![better](https://github.com/kurtekat/shaiya-episode-6/assets/106511299/a44a12bb-c29e-4a86-8993-fdc88d6b55a7)

**Comment by kurtekat** [comment]
no problem. good luck.
