### ISSUE TITLE
Episode 5 - Itemmal Point

### ISSUE THREAD

**Issue by melihxrist** [kurtekat/shaiya-episode-6#67]
Hello, I set up the ep5.4 server using your files.  I read all the SQL files and everything works smoothly, but for example, if you buy a paid product from itemmal and relog, the fee is refunded and the item remains in the bag.

**Comment by kurtekat** [comment]
what version of sdev are you using?

**Comment by melihxrist** [comment]
Also, sometimes when I buy something from itemmal, DC occurs, sometimes it happens all the time, sometimes it happens occasionally.

**Comment by kurtekat** [comment]
it's all related. i tried to fix another bug that was reported, but i ended up trading one bug for two. all the bugs go away when i use the ep4 dbAgent, so i'm looking for the difference in behavior.

**Comment by melihxrist** [comment]
Hmm, will there be a problem if I use ep4.5 dbAgent until you solve the problem?

**Comment by kurtekat** [comment]
> Hmm, will there be a problem if I use ep4.5 dbAgent until you solve the problem?

i don't know. as long as it can find all the stored procedures, it may be ok.

**Comment by kurtekat** [comment]
https://github.com/kurtekat/shaiya-episode-6/commit/ae330645748143327e63b9d66160e2576620a776

this solves your issue (i think), but it has bug i tried to fix last time. i have no idea when it will be fixed.

**Comment by melihxrist** [comment]
> https://github.com/kurtekat/shaiya-episode-6/commit/ae330645748143327e63b9d66160e2576620a776
> 
> this solves your issues (i think), but it has the bug i tried to fix last time. it's gonna take me a while to figure it out.

Okey, I will get back to you after testing

**Comment by melihxrist** [comment]
The problem I mentioned has been solved, thank you, good job.  I will let you know if I experience DC issue

**Comment by kurtekat** [comment]
i found a mod in the dbAgent file. i checked the ep4 and ep3 version and neither had this modification, which explains why the bug went away when i used the ep4 file. i'm about to replace it.

```
// wrong

00407942  MOV DWORD PTR DS:[EBX+8],1

// right

00407942  MOV DWORD PTR DS:[EBX+8],0
```
