### ISSUE TITLE
chaotic square item list does not appear (dll import)

### ISSUE THREAD

**Issue by Sagwa094** [kurtekat/shaiya-episode-6#68]
Hello, I followed your instructions for chaotic square but when I try to use the resource, the items do not appear in the crafting list

Can you help me with this? I'm using item 79 28 (Cauldron Dash)
![sq](https://github.com/kurtekat/shaiya-episode-6/assets/143913672/9f295d97-76b3-4bfc-a9f4-0c723cfea4af)

![sq2](https://github.com/kurtekat/shaiya-episode-6/assets/143913672/685e399c-5505-481b-b63f-d1bc0a544e73)

**Comment by kurtekat** [comment]
how are you loading sdev?

**Comment by kurtekat** [comment]
ok. there have been some issues related to filesystem operations. if the dll is loaded too soon, i can't read the files. it can't log the error for the same reason. see the **Injection** section i added to the wiki.

try injecting the dll with cheat engine and see if the list shows up. it worked for another user that had the same issue.

**Comment by Sagwa094** [comment]
attacked of loading the dll with stud_pe, and I still have the same problem

**Comment by kurtekat** [comment]
> attacked of loading the dll with stud_pe, and I still have the same problem

the other user was using a stud_pe import too

**Comment by Sagwa094** [comment]
everything went well with cheat engine

**Comment by Sagwa094** [comment]
Thanks for the info

**Comment by kurtekat** [comment]
sadly, the only solutions i have for this at the moment are gross. i'll leave this issue open for now.

**Comment by Sagwa094** [comment]
Maybe if you add a delay to execute the dll's functions when ps_game starts, it should resolve this issue.

**Comment by Sagwa094** [comment]
example: starting ps_game, the dll is loaded by it, but the functions are only started after 10 seconds

**Comment by kurtekat** [comment]
> example: starting ps_game, the dll is loaded by it, but the functions are only started after 10 seconds

that's an example of what i don't want to do. in spite of that, i'll add an example to get people past this issue for now. include <thread> at the top of main.cpp and do this in **Main**. if 2 seconds isn't enough, add 1 second until it works. this is so gross xD

```cpp
std::thread([=] {
    std::this_thread::sleep_for(std::chrono::seconds(2));

    #ifdef SHAIYA_EP6_ITEM_SET
    Synergy::init();
    #endif

    #ifdef SHAIYA_EP6_ITEM_SYNTHESIS
    Synthesis::init();
    #endif

    }).detach();
```

**Comment by Sagwa094** [comment]
> > example: starting ps_game, the dll is loaded by it, but the functions are only started after 10 seconds
> 
> that's an example of what i don't want to do.
> 
> in spite of that, i'll add a snip to get people past this issue for now. include `<thread>` at the top of main.cpp and do this in **Main**. if 2 seconds isn't enough, add 1 second until it works. this is so gross.
> 
> ```c++
> std::thread([=] {
>     std::this_thread::sleep_for(std::chrono::seconds(2));
> 
>     #ifdef SHAIYA_EP6_ITEM_SET
>     Synergy::init();
>     #endif
> 
>     #ifdef SHAIYA_EP6_ITEM_SYNTHESIS
>     Synthesis::init();
>     #endif
> 
>     }).detach();
> ```

worked perfectly

**Comment by kurtekat** [comment]
so, it seems the problem is the current working directory not being resolved. i'm reluctant to add a workaround to the library. i might add some code to the wiki instead.

**Comment by kurtekat** [comment]
https://github.com/kurtekat/shaiya-episode-6/commit/24b97f633a7fb0077cb1e52fba0c6241a6f3eca6
https://github.com/kurtekat/shaiya-episode-6/wiki/Getting-Started#export

@Sagwa094 please let me know if this is solved.

**Comment by WilliamZanetti1** [comment]
any solution found? I managed to import up to item 36, after that it no longer works.
![Screenshot_104](https://github.com/kurtekat/shaiya-episode-6/assets/100011617/f70f683a-3603-4d0b-9d32-dcee9f62c804)

**Comment by kurtekat** [comment]
@WilliamZanetti1 see #77
