### ISSUE TITLE
Suggestion: EP5.4 - Confirm Button

### ISSUE THREAD

**Issue by melihxrist** [kurtekat/shaiya-episode-6#69]
Hello mate, i have a suggestion. As everyone knows, there is a Confirm Button DC problem in ep5.4.  Can you integrate this directly into the sdev.dll file without a script so we don't have to search for a separate compatible script

**Comment by kurtekat** [comment]
https://github.com/kurtekat/shaiya-episode-6/blob/main/server/sdev/src/packet_exchange.cpp
https://github.com/kurtekat/shaiya-episode-6/blob/dde367cc308b72f4329ad2775194bd2fb22fc81c/server/sdev/include/shaiya/packets/0A00.h#L91

the library supports that packet. it's gets compiled whether an ep6 macro is defined or not.

**Comment by kurtekat** [comment]
> Yes, it was fixed when I updated the files, thanks. But some players reported that the item disappeared after doing relog, CC and similar things after the trade. I really don't know if there is such a problem, but the server also reported

the dbAgent in this repo had an issue like that will item mall items. it could be related. i'm not sure if you seen this post.

https://github.com/kurtekat/shaiya-episode-6/issues/67#issuecomment-1885855117

i'll check it later, just to be sure.

**Comment by kurtekat** [comment]
i did a transaction, relogged both characters and the item didn't disappear. if you get another report like this, open another issue and use the bug report template so i will have all the information i need to reproduce the issue.

**Comment by melihxrist** [comment]
> i did a transaction, relogged both characters and the item didn't disappear. if you receive a report like this again, open another issue and use the bug report template so i will have all the information i need to reproduce the issue.

Okey, thank so much for help. Good luck friend
