### ISSUE TITLE
sdev.dll Injection

### ISSUE THREAD

**Issue by sjrgensen** [kurtekat/shaiya-episode-6#70]
doesnt work on Windows Server 2016, sdev.dll Injection crash ps game. installed the redistributable from the link in the wiki still same
![image](https://github.com/kurtekat/shaiya-episode-6/assets/156950644/787a987d-1896-41ba-88c3-1403ced5e966)

**Comment by kurtekat** [comment]
is that ps_game from this repo? if so, is it v1 or v2?

**Comment by kurtekat** [comment]
please upload that ps_game, the NPCQuest.SData from that Data folder and the files in the Log directory.
