### ISSUE TITLE
Item Disappear after Trade

### ISSUE THREAD

**Issue by melihxrist** [kurtekat/shaiya-episode-6#71]
**Description the Bug**
I received feedback from many players about the problem I mentioned recently.  I learned the problem in more detail through the players' test. This problem occurs with stacked items.  So, for example, you have 20 lapisias. If you trade 10 of them, the remaining 10 will disappear the next time you enter the game.

**To Reproduce**
1. If you make a trade (stacked item) and then exit the game, relog and enter again, the remaining item will be lost.

**Additional context**
If you add the remaining item to the warehouse after the trade, the item will not be lost.

**Comment by kurtekat** [comment]
if your CTs are ok, here's a list of procedures that may have been edited.

```
PS_GameLog

usp_Insert_Action_Log_E

PS_GameData

usp_Read_Char_Items_Detail_R
usp_Read_Char_Items_Simple_R
usp_Save_Char_Item_Add_E
usp_Save_Char_Item_Mod_E
usp_Save_Char_Item_Mod_E
```

also, you may want to check if someone added a trigger to this table.

```
CharItems
```

**Comment by melihxrist** [comment]
OK, I'll check what you said when I get home tomorrow.  Yes, I saw your comment and made the changes you told me there.  After doing what you said, there was no DC problem with Itemmal, but I don't know if it could trigger this.

**Comment by WilliamZanetti1** [comment]
> **Description the Bug** I received feedback from many players about the problem I mentioned recently. I learned the problem in more detail through the players' test. This problem occurs with stacked items. So, for example, you have 20 lapisias. If you trade 10 of them, the remaining 10 will disappear the next time you enter the game.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. If you make a trade (stacked item) and then exit the game, relog and enter again, the remaining item will be lost.
> 
> **Additional context** If you add the remaining item to the warehouse after the trade, the item will not be lost.


I did the test, and I had no problems, it repeats more than once, and I have many active ct, there is probably a problem with your database

**Comment by kurtekat** [comment]
@melihxrist , i'm not sure if you know this, but SQL Server Profiler can be very helpful in these situations. it will show you every procedure that gets called when you do the transaction, relog, etc.

**Comment by melihxrist** [comment]
Okey, I will get back to you after trying the procedures mates

**Comment by WilliamZanetti1** [comment]
take a look at the ps_gamelog too, if there are any transaction errors

**Comment by melihxrist** [comment]
> if your CTs are ok, here's a list of procedures that should be checked.
> 
> ```
> PS_GameLog
> 
> usp_Insert_Action_Log_E
> 
> PS_GameData
> 
> usp_Read_Char_Items_Detail_R
> usp_Read_Char_Items_Simple_R
> usp_Save_Char_Item_Add_E
> usp_Save_Char_Item_Mod_E
> usp_Save_Char_Item_Mod_E
> ```
> 
> also, you may want to check if someone added a trigger to this table.
> 
> ```
> CharItems
> ```

I checked these by comparing another database, but I couldn't see a problem. But I think it's about procedure. Can you send me your ep5.4 database so I can make a better comparison

**Comment by melihxrist** [comment]
@

**Comment by melihxrist** [comment]
> > Can you send me your ep5.4 database so I can make a better comparison
> 
> please send me your `usp_Insert_Action_Log_E` procedure before we get into anything else. your log files may help as well, so send those too, if you don't mind. a zip file would be nice.

Sure bro. 
[Uploading ActionLog.zip…]()

**Comment by kurtekat** [comment]
i commented out two actions. both related to trading. one may be deleting the items. i suspected it may be in there, which is why i wanted to see it. i also added a snip to escape single quotes in item, mob, and skill names, so you'll stop having those failed insert errors.

[ActionLog-edited.zip](https://github.com/kurtekat/shaiya-episode-6/files/13992516/ActionLog-edited.zip)

please let me know if the problem goes away.

**Comment by melihxrist** [comment]
> i commented out two actions. both of them are related to trading. one may be deleting the items. i suspected it may be in there, which is why i wanted to see it. i also added a snip to escape single quotes in item, mob, and skill names, so you'll stop having those failed insert errors.
> 
> [ActionLog-edited.zip](https://github.com/kurtekat/shaiya-episode-6/files/13992516/ActionLog-edited.zip)
> 
> please let me know if the problem goes away.

Yes it worked, thank you very much. Thanks for both files and information. what's the problem? Can you give me information so that I can increase my knowledge

**Comment by kurtekat** [comment]
> what's the problem?

perhaps the `Leave` column isn't being updated properly? i don't know. i don't think it really matters. the [dbAgent](https://www.elitepvpers.com/forum/shaiya-pserver-guides-releases/3798719-release-episode-5-4-packet-based-dupe-fix.html) in this repo and [this](https://github.com/kurtekat/shaiya-episode-6/blob/c3dda4217b228a4f5a9a2cc9799d3c802ddd651e/server/sdev/sql/%5Bdbo%5D.%5Busp_Save_Char_Info_E%5D.sql#L56) (credits to lilprohacker) should solve this kind of dupe. invalid (e.g. `NaN`)  `x` and `z` positions are the enemy.

**Comment by WilliamZanetti1** [comment]
> > i commented out two actions. both of them are related to trading. one may be deleting the items. i suspected it may be in there, which is why i wanted to see it. i also added a snip to escape single quotes in item, mob, and skill names, so you'll stop having those failed insert errors.
> > [ActionLog-edited.zip](https://github.com/kurtekat/shaiya-episode-6/files/13992516/ActionLog-edited.zip)
> > please let me know if the problem goes away.
> 
> Yes it worked, thank you very much. Thanks for both files and information. what's the problem? Can you give me information so that I can increase my knowledge

A very important tip about action_log, create separate triggers for each function, this way you don't overload the sql having to execute 400 lines more than 50 times per second, if you have many players online, in my case the fluidity improved after I started creating they separate.
