### ISSUE TITLE
/ntcn (/ntplayer)

### ISSUE THREAD

**Issue by WilliamZanetti1** [kurtekat/shaiya-episode-6#72]
Is it possible to add the /ntcn(/ntplayer) commands to ps_game? If it already is, I haven't found it.

**Comment by kurtekat** [comment]
Cups wrote something that should work. this is a fork of the repository.

https://github.com/EchoTemp/shaiya-library/blob/master/shaiya/src/shaiya/hooks/command/CommandManager.cpp

i would try using this packet to send the message. it's used by the /wnotice command.

https://github.com/kurtekat/shaiya-episode-6/blob/a39e1254aae0bb52e59eb0071c6843fe4dee8833/server/sdev/include/shaiya/packets/F900.h#L20

**Comment by melihxrist** [comment]
How do we do this kind of thing?  I want to add things like /ntcn /move to ps_game, but I have no knowledge of C++ or packages and I don't know what is what and how to do it.  Can you explain it as if you were explaining it to a child? 😅

**Comment by kurtekat** [comment]
> How do we do this kind of thing? I want to add things like /ntcn /move to ps_game, but I have no knowledge of C++ or packages and I don't know what is what and how to do it. Can you explain it as if you were explaining it to a child? 😅

i would start by adding a new header to this directory for your command.
https://github.com/EchoTemp/shaiya-library/tree/master/shaiya/include/shaiya/hooks/command/impl

then, add a source file to this directory.
https://github.com/EchoTemp/shaiya-library/tree/master/shaiya/src/shaiya/hooks/command/impl

you should be able to use the `PlayerTeleportCommand` code as a boiler plate. i've already given a lot of examples of how to send a packet in my library. i've never used the other library, so you're just gonna have to try it out.

truth: i've spent roughly 3 years building this project. i can't teach you (or anyone else) how to do this stuff.
