### ISSUE TITLE
inspect bug

### ISSUE THREAD

**Issue by im-razor** [kurtekat/shaiya-episode-6#74]
**Describe the bug**
we inspect one of them, our own items appear.

**Screenshots**
![Shaiya0000](https://github.com/kurtekat/shaiya-episode-6/assets/79925277/fa6c9442-1203-4092-ba09-7dd2b165da43)
![Shaiya0001](https://github.com/kurtekat/shaiya-episode-6/assets/79925277/9a7b9b16-0161-4573-9e2e-c238ed5e63e4)

**Comment by kurtekat** [comment]
https://github.com/kurtekat/shaiya-episode-6/commit/140b679ddf09f443495fb75718c8f6bd014a21de
