### ISSUE TITLE
Skin faction (enable world enter cross faction)

### ISSUE THREAD

**Issue by im-razor** [kurtekat/shaiya-episode-6#75]
**Describe the bug**
with pet.dll we could have a cross-faction view but now we can't do that, it disconnects

**for ps_game offset**
//enable login cross faction (light)
47B54E:
jmp 47B6BB

//enable login cross faction (dark)
47B608:
jmp 47B6BB

//enable world enter cross faction
47C134:
jmp 47C180

**Comment by kurtekat** [comment]
thanks, but i'm not interested in adding stuff like this to the library.

**Comment by im-razor** [comment]
Do you have any idea how to activate it? Because this even worked in the original game, but your library prevents it from working

**Comment by kurtekat** [comment]
no. i just checked and i don't see any code in the library that bypasses the addresses. i don't know what to tell you.

**Comment by im-razor** [comment]
Ok I took care of it myself thanks
