### ISSUE TITLE
chaotic square issue

### ISSUE THREAD

**Issue by kurtekat** [kurtekat/shaiya-episode-6#77]
any solution found? I managed to import up to item 36, after that it no longer works.
![Screenshot_104](https://github.com/kurtekat/shaiya-episode-6/assets/100011617/f70f683a-3603-4d0b-9d32-dcee9f62c804)

_Originally posted by @WilliamZanetti1 in https://github.com/kurtekat/shaiya-episode-6/issues/68#issuecomment-1911312178_

**Comment by kurtekat** [comment]
what stops working? please be more specific.

i put 41 items in my config file to test the problem. it sends all the items to the client and works as expected.

aside from that, make sure item 102121 is set to effect 99. otherwise, it will not work.

**Comment by WilliamZanetti1** [comment]
It's configured, only 37 and 38 don't appear, I've redid them a few times, and put others that already work for testing.

> i put 41 items in my config file to test the problem. it sends all the items to the client and works as expected. aside from that, make sure item 102121 is set to effect 99. otherwise, it will not work.

**Comment by kurtekat** [comment]
> It's configured, only 37 and 38 don't appear, I've redid them a few times, and put others that already work for testing.

so, itemId 102121 is set to effect 99?

**Comment by WilliamZanetti1** [comment]
> > It's configured, only 37 and 38 don't appear, I've redid them a few times, and put others that already work for testing.
> 
> so, itemId 102121 is set to effect 99?

yes, I'm checking all items again from item synthesis

**Comment by WilliamZanetti1** [comment]
Well, I did a test to ensure that the problem wasn't in the numbers, and it appeared in the other chaotic that I had already been using, wouldn't there be a limit on how many different items can be used as chaotic?
![Screenshot_105](https://github.com/kurtekat/shaiya-ep
![Screenshot_108](https://github.com/kurtekat/shaiya-episode-6/assets/100011617/b81b46f7-bd54-47aa-9e79-973b71040387)
isode-6/assets/100011617/58d8a81d-8e1c-44a9-827d-078017fac237)

**Comment by WilliamZanetti1** [comment]
This image below is from chaotic 102 121
![Screenshot_106](https://github.com/kurtekat/shaiya-episode-6/assets/100011617/58feb14e-28fa-4249-b9f7-5b3af9e6822b)

**Comment by kurtekat** [comment]
ok. please send me the item.sdata and the ini in a zip file, so i can try them out.

**Comment by WilliamZanetti1** [comment]
`;PSM_Client\Bin\Data\ItemSynthesis.ini

[ItemSynthesis_0]
ItemID=102094
SuccessRate=85
MaterialType=100,100,100,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialTypeID=194,193,199,198,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialCount=3,3,3,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CreateType=100
CreateTypeID=82
CreateCount=1

[ItemSynthesis_1]
ItemID=102094
SuccessRate=85
MaterialType=100,100,100,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialTypeID=194,193,199,198,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialCount=30,30,30,30,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CreateType=100
CreateTypeID=82
CreateCount=10

[ItemSynthesis_2]
ItemID=102094
SuccessRate=85
MaterialType=100,100,100,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialTypeID=194,193,199,198,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialCount=60,60,60,60,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CreateType=100
CreateTypeID=82
CreateCount=20

[ItemSynthesis_3]
ItemID=102095
SuccessRate=85
MaterialType=100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialTypeID=82,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialCount=20,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CreateType=100
CreateTypeID=192
CreateCount=1

[ItemSynthesis_4]
ItemID=102095
SuccessRate=85
MaterialType=100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialTypeID=140,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialCount=40,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CreateType=100
CreateTypeID=141
CreateCount=1

[ItemSynthesis_5]
ItemID=102096
SuccessRate=85
MaterialType=102,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialTypeID=86,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialCount=20,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CreateType=102
CreateTypeID=90
CreateCount=1

[ItemSynthesis_6]
ItemID=102096
SuccessRate=85
MaterialType=102,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialTypeID=86,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialCount=20,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CreateType=102
CreateTypeID=89
CreateCount=1

[ItemSynthesis_7]
ItemID=102098
SuccessRate=85
MaterialType=100,100,100,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialTypeID=254,254,254,254,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialCount=20,20,20,20,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CreateType=102
CreateTypeID=88
CreateCount=1

[ItemSynthesis_8]
ItemID=102099
SuccessRate=85
MaterialType=102,102,102,102,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialTypeID=88,88,88,88,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialCount=20,20,20,20,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CreateType=102
CreateTypeID=87
CreateCount=1

[ItemSynthesis_9]
ItemID=102100
SuccessRate=85
MaterialType=102,100,100,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialTypeID=85,171,171,171,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialCount=1,5,5,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CreateType=101
CreateTypeID=10
CreateCount=1

[ItemSynthesis_10]
ItemID=102100
SuccessRate=85
MaterialType=102,100,100,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialTypeID=85,171,171,171,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialCount=5,25,25,25,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CreateType=101
CreateTypeID=10
CreateCount=5

[ItemSynthesis_11]
ItemID=102100
SuccessRate=85
MaterialType=102,100,100,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialTypeID=85,171,171,171,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialCount=1,5,5,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CreateType=101
CreateTypeID=11
CreateCount=1

[ItemSynthesis_12]
ItemID=102100
SuccessRate=85
MaterialType=102,100,100,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialTypeID=85,171,171,171,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialCount=5,25,25,25,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CreateType=101
CreateTypeID=11
CreateCount=5

[ItemSynthesis_13]
ItemID=102100
SuccessRate=85
MaterialType=102,100,100,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialTypeID=85,171,171,171,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialCount=1,5,5,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CreateType=101
CreateTypeID=12
CreateCount=1

[ItemSynthesis_14]
ItemID=102100
SuccessRate=85
MaterialType=102,100,100,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialTypeID=85,171,171,171,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialCount=5,25,25,25,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CreateType=101
CreateTypeID=12
CreateCount=5

[ItemSynthesis_15]
ItemID=102100
SuccessRate=85
MaterialType=102,100,100,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialTypeID=85,171,171,171,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialCount=1,5,5,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CreateType=101
CreateTypeID=13
CreateCount=1

[ItemSynthesis_16]
ItemID=102100
SuccessRate=85
MaterialType=102,100,100,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialTypeID=85,171,171,171,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialCount=5,25,25,25,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CreateType=101
CreateTypeID=13
CreateCount=5

[ItemSynthesis_17]
ItemID=102100
SuccessRate=85
MaterialType=102,100,100,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialTypeID=85,171,171,171,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialCount=1,5,5,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CreateType=101
CreateTypeID=14
CreateCount=1

[ItemSynthesis_18]
ItemID=102100
SuccessRate=85
MaterialType=102,100,100,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialTypeID=85,171,171,171,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialCount=5,25,25,25,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CreateType=101
CreateTypeID=14
CreateCount=5

[ItemSynthesis_19]
ItemID=102100
SuccessRate=85
MaterialType=102,100,100,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialTypeID=85,171,171,171,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialCount=1,5,5,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CreateType=101
CreateTypeID=15
CreateCount=1

[ItemSynthesis_20]
ItemID=102100
SuccessRate=85
MaterialType=102,100,100,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialTypeID=85,171,171,171,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialCount=5,25,25,25,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CreateType=101
CreateTypeID=15
CreateCount=5

[ItemSynthesis_21]
ItemID=102100
SuccessRate=85
MaterialType=102,100,100,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialTypeID=85,171,171,171,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialCount=1,5,5,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CreateType=101
CreateTypeID=16
CreateCount=1

[ItemSynthesis_22]
ItemID=102100
SuccessRate=85
MaterialType=102,100,100,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialTypeID=85,171,171,171,171,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialCount=5,25,25,25,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CreateType=101
CreateTypeID=16
CreateCount=5

[ItemSynthesis_23]
ItemID=102100
SuccessRate=85
MaterialType=102,100,100,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialTypeID=85,171,171,171,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialCount=1,5,5,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CreateType=101
CreateTypeID=17
CreateCount=1

[ItemSynthesis_24]
ItemID=102100
SuccessRate=85
MaterialType=102,100,100,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialTypeID=85,171,171,171,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialCount=5,25,25,25,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CreateType=101
CreateTypeID=17
CreateCount=5

[ItemSynthesis_25]
ItemID=102100
SuccessRate=85
MaterialType=102,100,100,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialTypeID=85,171,171,171,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialCount=1,5,5,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CreateType=101
CreateTypeID=18
CreateCount=1

[ItemSynthesis_26]
ItemID=102100
SuccessRate=85
MaterialType=102,100,100,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialTypeID=85,171,171,171,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialCount=5,25,25,25,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CreateType=101
CreateTypeID=18
CreateCount=5

[ItemSynthesis_27]
ItemID=102101
SuccessRate=85
MaterialType=30,30,30,30,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialTypeID=240,240,240,240,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialCount=3,3,3,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CreateType=30
CreateTypeID=241
CreateCount=1

[ItemSynthesis_28]
ItemID=102101
SuccessRate=85
MaterialType=30,30,30,30,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialTypeID=241,241,241,241,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialCount=3,3,3,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CreateType=30
CreateTypeID=242
CreateCount=1

[ItemSynthesis_29]
ItemID=102102
SuccessRate=85
MaterialType=102,102,102,102,102,102,102,102,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialTypeID=83,83,83,83,83,83,83,83,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialCount=10,10,10,10,10,10,10,10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CreateType=100
CreateTypeID=139
CreateCount=1

[ItemSynthesis_30]
ItemID=102102
SuccessRate=85
MaterialType=102,102,102,102,102,102,102,102,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialTypeID=83,83,83,83,83,83,83,83,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialCount=100,100,100,100,100,100,100,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CreateType=100
CreateTypeID=139
CreateCount=10

[ItemSynthesis_31]
ItemID=102102
SuccessRate=85
MaterialType=102,102,102,102,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialTypeID=81,81,82,82,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialCount=25,25,25,25,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CreateType=102
CreateTypeID=74
CreateCount=1

[ItemSynthesis_32]
ItemID=102102
SuccessRate=85
MaterialType=102,102,102,102,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialTypeID=74,74,74,74,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialCount=1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CreateType=102
CreateTypeID=75
CreateCount=1

[ItemSynthesis_33]
ItemID=102103
SuccessRate=85
MaterialType=100,100,100,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialTypeID=204,204,204,204,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialCount=7,7,7,7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CreateType=100
CreateTypeID=205
CreateCount=1

[ItemSynthesis_34]
ItemID=102103
SuccessRate=85
MaterialType=100,100,100,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialTypeID=205,205,205,205,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialCount=7,7,7,7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CreateType=100
CreateTypeID=206
CreateCount=1

[ItemSynthesis_35]
ItemID=102103
SuccessRate=85
MaterialType=100,100,100,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialTypeID=207,207,207,207,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialCount=7,7,7,7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CreateType=100
CreateTypeID=208
CreateCount=1

[ItemSynthesis_36]
ItemID=102103
SuccessRate=85
MaterialType=100,100,100,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialTypeID=208,208,208,208,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialCount=7,7,7,7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CreateType=100
CreateTypeID=209
CreateCount=1

[ItemSynthesis_37]
ItemID=102103
SuccessRate=85
MaterialType=100,100,100,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialTypeID=208,208,208,208,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialCount=7,7,7,7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CreateType=42
CreateTypeID=172
CreateCount=1

[ItemSynthesis_38]
ItemID=102103
SuccessRate=85
MaterialType=100,100,100,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialTypeID=208,208,208,208,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MaterialCount=7,7,7,7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CreateType=150
CreateTypeID=68
CreateCount=1`

**Comment by WilliamZanetti1** [comment]
> ok. please send me the item.sdata and the ini in a zip file, so i can try them with a debugger attached.

https://drive.google.com/file/d/0B5EvulrOFierYkswTTlranZhNUU/view?usp=sharing&resourcekey=0-nvlzpo-aaUVrSEbLLL_rjw

**Comment by kurtekat** [comment]
i get the item list when i use all the items in that config file. the list count matches what's in the ini. i also added 102121 to the ini and it works as expected.

> wouldn't there be a limit on how many different items can be used as chaotic?

no. you should be able to have as many as you can make.

**Comment by WilliamZanetti1** [comment]
I don't know what the problem is so, if it's using the same list, I'm injecting it through ce, is that the way to inject it into ps_game?

**Comment by kurtekat** [comment]
>  I'm injecting it through ce, is that the way to inject it into ps_game?

that's how i inject.

**Comment by kurtekat** [comment]
just be clear, injection doesn't matter anymore since i patched the dll import issue. 

here's the data, just in case. if it works for me, it should work for you too, i would think. although, i'm not sure what the difference would be. it would be really weird if the issue went away.

[Desktop.zip](https://github.com/kurtekat/shaiya-episode-6/files/14060623/Desktop.zip)

**Comment by WilliamZanetti1** [comment]
I did it, I just created another item, with another id, you'll know why haha
