### ISSUE TITLE
warehouse items disappear 

### ISSUE THREAD

**Issue by im-razor** [kurtekat/shaiya-episode-6#78]
**Describe the bug**
A lot of players say that objects disappear in the warehouse, this is a helmet or any items, to try this I filled my warehouse completely and waited 2 days but nothing disappeared. but a lot of players said that something disappeared from their warehouse

what to do to eliminate this problem or should we make a server-side packet logger to detect the problem

**Comment by kurtekat** [comment]
> a helmet or any items

the library will only remove an expired pet or costume and will send the notification packet to the client. that is, unless someone modified the logic.

> what to do to eliminate this problem or should we make a server-side packet logger to detect the problem

i think you should read #71 and follow my suggestions.
