### ISSUE TITLE
I tested the server alone and it ran very well. After entering some players, PS_ Game will crash

### ISSUE THREAD

**Issue by gaobbcdd** [kurtekat/shaiya-episode-6#79]
I tested the server alone and it ran very well. After entering some players, PS_ Game will crash
Here is the crash log：

2024-02-04 19:22:21 Exception !!!, code=0xC0000005, address=0x5B168D7A

Minidump write end.....................

0x5B168D7A sdev.dll: DllExport + 18858

0x5B168729 sdev.dll: DllExport + 17241

0x5B16E087 sdev.dll: DllExport + 40119

0x1D2EF860 <unknown module>: <unknown symbol>

Stack trace end.....................

Stack trace(all thread) begin.....................

2024-02-04 20:11:18 Exception !!!, code=0xC0000005, address=0x5B198D7A

Minidump write end.....................

0x5B198D7A sdev.dll: DllExport + 18858

0x5B198729 sdev.dll: DllExport + 17241

0x5B19E087 sdev.dll: DllExport + 40119

Stack trace end.....................

Stack trace(all thread) begin.....................

2024-02-04 20:22:31 Exception !!!, code=0xC0000005, address=0x5CF38D7A

Minidump write end.....................

0x5CF38D7A sdev.dll: DllExport + 18858

0x5CF38729 sdev.dll: DllExport + 17241

0x5CF3E087 sdev.dll: DllExport + 40119

Stack trace end.....................

Stack trace(all thread) begin.....................

2024-02-04 21:20:42 Exception !!!, code=0xC0000005, address=0x77DF40BC

Minidump write end.....................

0x77DF40BC ntdll.dll: RtlUdiv128 + 21596

0x77DA79E0 ntdll.dll: RtlAllocateHeap + 1200

0x77DA756E ntdll.dll: RtlAllocateHeap + 62

0x00520658 ps_game.exe: <unknown symbol>

0x0051B28A ps_game.exe: <unknown symbol>

0x004635C8 ps_game.exe: <unknown symbol>

0x00428AAB ps_game.exe: <unknown symbol>

Stack trace end.....................

Stack trace(all thread) begin.....................

**Comment by kurtekat** [comment]
send me that ps_game and that sdev.dll, so i can try with my local server.

**Comment by kurtekat** [comment]
did you write any code in DllExport?

```
2024-02-04 20:11:18 Exception !!!, code=0xC0000005, address=0x5B198D7A
Minidump write end.....................
0x5B198D7A sdev.dll: DllExport + 18858
0x5B198729 sdev.dll: DllExport + 17241
0x5B19E087 sdev.dll: DllExport + 40119
```

**Comment by gaobbcdd** [comment]
Sorry, I just replaced version 1.3.7.26. Old sdve.dll deleted。
this is version 1.3.7.26
2024-02-05 14:38:18 Exception !!!, code=0xC0000005, address=0x5B388D6A

Minidump write end.....................

0x5B388D6A sdev.dll: shaiya::Synergy::getWornSynergies + 154	D:\a\shaiya-episode-6\shaiya-episode-6\server\sdev\include\shaiya\src\Synergy.cpp, Line 166

0x5B388719 sdev.dll: shaiya::Synergy::applySynergies + 105	D:\a\shaiya-episode-6\shaiya-episode-6\server\sdev\include\shaiya\src\Synergy.cpp, Line 93

0x5B38E137 sdev.dll: naked_0x461D10 + 7	D:\a\shaiya-episode-6\shaiya-episode-6\server\sdev\src\user_equipment.cpp, Line 334

0x0046C325 ps_game.exe: <unknown symbol>

Stack trace end.....................



Stack trace(all thread) begin.....................

**Comment by gaobbcdd** [comment]
this is my ps_game [https://mega.nz/file/mU9RCYRA#nJIc_yo7NAfVVRfBDMP_gNRCinB4SFWTkbKQpcUS63c](url)

**Comment by kurtekat** [comment]
> this is my ps_game [https://mega.nz/file/mU9RCYRA#nJIc_yo7NAfVVRfBDMP_gNRCinB4SFWTkbKQpcUS63c](url)

i can't download it. will you upload it here, please?

**Comment by kurtekat** [comment]
it didn't crash.

[ps_game.zip](https://github.com/kurtekat/shaiya-episode-6/files/14169418/ps_game.zip)

try this one, without cheat engine scripts. let me know what happens.

**Comment by kurtekat** [comment]
![Capture](https://github.com/kurtekat/shaiya-episode-6/assets/142125482/701e835b-0209-44f7-87fe-f8ac0d876456)

if you inject those dlls alongside mine (as-is), the result it not going to be good. i'm pretty sure that's not the issue here, but i feel like it's important to note.

**Comment by kurtekat** [comment]
@gaobbcdd are you still with me?

**Comment by gaobbcdd** [comment]
The test has been running well until now, and I have always suspected that it is an issue with the injection point. I didn't use any other scripts. But using CT injection runs well

**Comment by kurtekat** [comment]
this is the difference in the one i uploaded. 

![Capture](https://github.com/kurtekat/shaiya-episode-6/assets/142125482/cc2f5101-4ea3-406d-a8a6-f9c490178c68)

if you want to inject it with cheat engine, use the one in the v2 directory from the repo, so the dll isn't loaded twice. i'm gonna close this as resolved.

**Comment by kurtekat** [comment]
the item duration code has been removed, which should solve the issue that caused your crash.
