### ISSUE TITLE
WH Bug

### ISSUE THREAD

**Issue by im-razor** [kurtekat/shaiya-episode-6#81]
As seen in the video, the item disappears in the warehouse, it does not always happen, but it happens in most of the players. I've tried many times after complaints, but I've only succeeded once, but it's a big problem because it happens in the majority of players, even if it doesn't happen all the time.

https://youtu.be/x_8K6LdpHxg

**Comment by kurtekat** [comment]
i see you teleport twice, then access the warehouse. i don't see what was in there before. aside from that, the library sends a notification to the client when it removes an item. if you really think the library is the cause, comment line 124 in main.cpp and retest.

```cpp
//hook::item_duration();
```

**Comment by kurtekat** [comment]
when an item is removed from the warehouse, it sends a packet to the gameLog service, so that's another way to verify.

https://github.com/kurtekat/shaiya-episode-6/blob/fc46aba5d94b7a896673e73f257c0fc71202ab6e/server/sdev/src/item_duration.cpp#L38

**Comment by im-razor** [comment]
//hook::item_duration(); I already did it this way because it was preventing me from keeping the game active because I was having problems with item durations, and it's been about 2-3 days since I did this and no one complained about items disappearing, so I think the problem is due to this cpp

**Comment by im-razor** [comment]
I tried this and it's still the same..


https://www.youtube.com/watch?v=uoODOHEPezY

**Comment by kurtekat** [comment]
> I tried this and it's still the same..
> 
> https://www.youtube.com/watch?v=uoODOHEPezY

tried what?

**Comment by kurtekat** [comment]
i can't reproduce this issue. before i give up, will you upload your dbAgent?

**Comment by kurtekat** [comment]
the code that would remove an item can't be accesses unless `ItemHasDuration` returns true. those bars would return false. have you made any changes to the source code? if so, i need to see what you've done.

**Comment by kurtekat** [comment]
> I think the problem is due to this cpp

the code in that cpp isn't executing the function that would remove an item from the warehouse unless `ItemHasDuration` returns true, which is not possible with the items in the video.

https://github.com/kurtekat/shaiya-episode-6/blob/fc46aba5d94b7a896673e73f257c0fc71202ab6e/server/sdev/include/shaiya/src/ItemDuration.cpp#L4

**Comment by kurtekat** [comment]
the only thing i can add, is it looks to me like it isn't saving correctly. you could upload your dbAgent here and let me compare it to mine. aside from that, i really don't know what i can do to help unless i have all your CTs, which is something i don't want to get into with anyone for obvious reasons.
