### ISSUE TITLE
Stats bug

### ISSUE THREAD

**Issue by im-razor** [kurtekat/shaiya-episode-6#83]
As you will see in the video a stats bug is happening

https://youtu.be/ZMsXQCIf5zM

**Comment by kurtekat** [comment]
i can barely see that. is the resist going negative?

**Comment by im-razor** [comment]
> i can barely see that. is the resist going negative?

yes it's negative, in fact it's not only negative, sometimes it's positive and it's not only in resistance, it happens randomly.

**Comment by kurtekat** [comment]
does it happen without any other code injected aside from mine?

**Comment by im-razor** [comment]
yea only your codes

**Comment by kurtekat** [comment]
i'll check it out within the next day or so.

**Comment by im-razor** [comment]
ok if you want to communicate faster and I can help with testing
Discord: im.razor

> i'll check it out within the next day or so.

**Comment by kurtekat** [comment]
my discord account is disabled.

**Comment by kurtekat** [comment]
> yea only your codes

i see you are adding/removing a skin and something in another slot that i don't have in my inventory. why are you telling me this is only with my code? the library doesn't support either of those slots.
