### ISSUE TITLE
Weapon and Shield skin display bug

### ISSUE THREAD

**Issue by im-razor** [kurtekat/shaiya-episode-6#84]
There is a display problem for the shield and weapon costume, which is caused by your user_shape.cpp 
`
// CZone::SendUserShape`
` util::detour((void*)0x426948, naked_0x426948, 7); 
 `
actually shouldn't be a problem, but what this causes is 

`unsigned u0x426CA0 = 0x426CA0;  `Because you enter this offset as jmp and for the weapon and shield costume that everyone uses around, offset `00426C34 ` is invalid, so the costume and shield skin does not appear in the game, you can make another correction for this, or I took `naked_0x426948  `to the comment line and made a different correction myself. just writing this in case you fix it.

**Comment by kurtekat** [comment]
do you mean my code is interfering with CT scripts for skins?

**Comment by kurtekat** [comment]
change the CT or change the code in your fork.

**Comment by im-razor** [comment]
I fixed it for myself, but if this project is to create a pet.dll, there was no such problem for the pet.dll

**Comment by kurtekat** [comment]
i don't feel like i need to patch my code to be compatible with a CT script that i've never seen. why don't you go back to using pet.dll? this whole issue is asinine.
