### ISSUE TITLE
Mounts Bug

### ISSUE THREAD

**Issue by im-razor** [kurtekat/shaiya-episode-6#85]
When we teleport on the map, the new mount view is bugs, you can see this by watching the video

https://youtu.be/RsCftGb2Xoo

**Comment by kurtekat** [comment]
i'm not adding those mounts to my client to check this out. unless you can show me where my library causes this issue, you're on your own.

**Comment by kurtekat** [comment]
if you want to motivate me to check this, do what you didn't in the video with a packet sniffer attached and send me the output.

**Comment by kurtekat** [comment]
@im-razor check with my last commit

**Comment by kurtekat** [comment]
i marked this as a bug because i found a mistake in my shape code (see the commit) related to vehicles. if it solves your issue, great. the code i patched is executed when you teleport, so i guess we'll see what happens. the packets are correct.

**Comment by im-razor** [comment]
The problem has been fixed thank you

> i marked this as a bug because i found a mistake in my vehicle shape code (see the commit). the code i patched is executed when you teleport, so i guess we'll see what happens. the packets are correct.

**Comment by kurtekat** [comment]
thanks for reporting it.
