### ISSUE TITLE
After failing to link gemstones, the synergy effect will disappear when returning to the character

### ISSUE THREAD

**Issue by gaobbcdd** [kurtekat/shaiya-episode-6#87]
Synergy effect: Armors or jewelry that activate the synergy effect on the body will still have the synergy effect attribute in effect after being loaded with stones or broken due to failure to retrieve them. After returning to the character, the synergy effect will become invalid

**Comment by kurtekat** [comment]
ok. i'll check this out as soon as i can.

**Comment by kurtekat** [comment]
will you provide some reproduction steps?

1. do this
2. do this
3. and so on...

**Comment by kurtekat** [comment]
ok. understand what you mean. i'll try to have it fixed today.

**Comment by kurtekat** [comment]
i understand why this is happening, but it's gonna be more tricky than i thought to make it right. i think it needs to be patched in the lapisian function too for the same reason.

**Comment by kurtekat** [comment]
@gaobbcdd 

will you test this patch, please?

[test patch.zip](https://github.com/kurtekat/shaiya-episode-6/files/15044886/test.patch.zip)

**Comment by gaobbcdd** [comment]
yes i test it's ok. Currently fixed
