### ISSUE TITLE
New slot equip bug

### ISSUE THREAD

**Issue by im-razor** [kurtekat/shaiya-episode-6#88]
sdev/src/user_equipment.cpp > Line 20
`
 if (slot > EquipmentSlot::Wings)
            return false;
            `
            This code you added prevents the slots added after Wing from working. Is it a problem to delete this?

**Comment by kurtekat** [comment]
i would replace `EquipmentSlot::Wings` with the highest slot you allow. if you've made use of all the equipment slots, then i'd replace it with `if (slot >= max_inventory_slot) return false;`, unless you are absolutely certain it's safe. i like to err on the side of caution when it comes to ranges.

**Comment by kurtekat** [comment]
i need to do some tests with packets and then i'll probably end up changing it anyhow. it caught my eye and i thought to add something there until i know it's ok.

**Comment by kurtekat** [comment]
i'm gonna remove it.

**Comment by gaobbcdd** [comment]
WeaponSkin Weapon fashion. Everyone needs it very much. This is the CT script. Can you integrate it into it

**Comment by gaobbcdd** [comment]
[ps_game weepskin.zip](https://github.com/kurtekat/shaiya-episode-6/files/15050782/ps_game.weepskin.zip)

**Comment by kurtekat** [comment]
you'll have to implement that on your own. it's outside the scope of this project.

**Comment by gaobbcdd** [comment]
ok，I am mainly concerned about compatibility issues. I have tried adding new slots. But it doesn't work

**Comment by kurtekat** [comment]
you should be able to set these to 24 safely (304-316)

https://github.com/kurtekat/shaiya-episode-6/blob/38e9b11042973905442119d310d6176f4bb7cb3b/sdev/src/user_equipment.cpp#L304

these arrays can be given a size of 24. then, i would pad 2 bytes at the end of `Character0403`.

https://github.com/kurtekat/shaiya-episode-6/blob/38e9b11042973905442119d310d6176f4bb7cb3b/sdev/include/shaiya/packets/dbAgent/0400.h#L9

set this to 24 so it will read 24 slots from the table.

https://github.com/kurtekat/shaiya-episode-6/blob/38e9b11042973905442119d310d6176f4bb7cb3b/sdev-db/src/character_list.cpp#L170

then, set some conditions in `user_equipment::enable_slot`

https://github.com/kurtekat/shaiya-episode-6/blob/38e9b11042973905442119d310d6176f4bb7cb3b/sdev/src/user_equipment.cpp#L18

**Comment by kurtekat** [comment]
that's just a starting point. i don't want to wrap my head around what everyone is trying to do with this project. i tested what i said to do and it worked properly. i don't really want to add it to the library officially.

**Comment by gaobbcdd** [comment]
thank you

**Comment by kurtekat** [comment]
no problem.

**Comment by kurtekat** [comment]
by the way, the memory writes at the first link are in your script. the function it calls to send the equipment is here:

https://github.com/kurtekat/shaiya-episode-6/blob/38e9b11042973905442119d310d6176f4bb7cb3b/sdev/include/shaiya/include/CUser.h#L655

everything you need is in the library, i'm sure. i would help more, but reading all that assembly makes me tired.

**Comment by gaobbcdd** [comment]
Thank you. When I use version 1.4.4, the character name does not appear. I don't know what the reason is

**Comment by gaobbcdd** [comment]
![image](https://github.com/kurtekat/shaiya-episode-6/assets/66864390/ce503665-f4d6-45b9-8e91-8dd557702c16)
When I set the slot to 24, the character name will disappear.

**Comment by gaobbcdd** [comment]
![image](https://github.com/kurtekat/shaiya-episode-6/assets/66864390/4c79842d-66ee-495a-968b-e23f61ae8335)

**Comment by kurtekat** [comment]
> ![image](https://private-user-images.githubusercontent.com/66864390/324357773-ce503665-f4d6-45b9-8e91-8dd557702c16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NzAxNzYsIm5iZiI6MTcxMzc2OTg3NiwicGF0aCI6Ii82Njg2NDM5MC8zMjQzNTc3NzMtY2U1MDM2NjUtZjRkNi00NWI5LThlOTEtOGRkNTU3NzAyYzE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDA3MTExNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0MzY3Y2NkNjMwYzZhOWFiNDYwZTRjMDVkYmZhYzgzZGM1OTY3MTU0YWM0YWY4OGMxMzZiZWUzNDhkY2I1ZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P0QocWjfoc70ErETUWiU8s5nvwfMgRtA7zrHH0OzdEE) When I set the slot to 24, the character name will disappear.

right. that's why i specified certain places to change the number. you don't want to change the constant, because it will affect the shape packets, etc., unless you know how to mod the client to accept 24 items :P

i can show you how to change the 0x101 and 0x303 handlers to 24 items if you upload your game.exe

**Comment by kurtekat** [comment]
if i were you, i would change that number to 24 where i specified and leave those packets alone unless you intend to be able to see the character wearing what you're putting in the new slots.

**Comment by kurtekat** [comment]
i'll explain one more time.

change these to 24. don't change the constant.

![Capture](https://github.com/kurtekat/shaiya-episode-6/assets/142125482/75daca71-aa76-4592-afdf-a4e458873989)

this to 24

```cpp
 #pragma pack(push, 1)
struct Equipment0403 
{
    Array<UINT8, 24> type;
    Array<UINT8, 24> typeId;
};
```

pad 2 bytes here to make it an even 120. i don't know if 118 will align properly.

![Capture](https://github.com/kurtekat/shaiya-episode-6/assets/142125482/545c8a6c-38c0-47d8-b1cc-13af684d7c8f)

**Comment by gaobbcdd** [comment]
ok.Thank you for letting me know how to add slots normally

**Comment by kurtekat** [comment]
here's some images, showing that it works. i don't know if it's solid or not, but the packets looks ok.

![Capture](https://github.com/kurtekat/shaiya-episode-6/assets/142125482/161b89f8-2870-40cb-b851-1ee72f12e87a)

![Capture2](https://github.com/kurtekat/shaiya-episode-6/assets/142125482/5bc3f94d-afc3-4786-a5a4-e9ca0e348952)

**Comment by kurtekat** [comment]
i removed that `max_equipment_slot` constant from the packet definitions. now, it should be as easy as changing `Equipment0403` array sizes to 24 (padding Character0403?) and setting `max_equipment_slot` to 24.
