### ISSUE TITLE
Issues with EP5 build and build 0x12092000

### ISSUE THREAD

**Issue by Spelunkern** [kurtekat/shaiya-episode-6#89]
Hey, im testing with the variant versions of the project and it seems they are not working as expected.

I suspect this is a very simple issue regarding the compilation and the client not receiving the correct packets, specifically on the macro sections.

I attach an image to show a portion of the issue, which it's much bigger but i think it doesn't matter because it's a problem with the library;  the same things happens if you try to run a game.exe that is uncompatible with the server files, so im sure this is just an small error.
![1](https://github.com/kurtekat/shaiya-episode-6/assets/150851205/7cf64b45-41ea-4ef3-aa55-af05ccc1102d)

**Comment by kurtekat** [comment]
ok. i'll check it out in a little while.

**Comment by kurtekat** [comment]
looks fine to me. did you inject the dbAgent library? that library is only for 6.4 clients. 5.4 and 6.0 don't need it. they have the same equipment specs.

**Comment by Spelunkern** [comment]
Yeah the db_agent was the problem, my bad!

Thank you
![1](https://github.com/kurtekat/shaiya-episode-6/assets/150851205/44cb7844-ed6b-40c5-9459-a73c8a8ffa8d)

I have a question about the client dll, all clients use the same one?  Haven't tested yet

**Comment by kurtekat** [comment]
the client dll is for `0x16021200`, which is the same one that CustomGame.dll supports.

**Comment by Spelunkern** [comment]
> the client dll is for `0x16021200`, which is the same version that CustomGame.dll supports.

Thats what i suppose, i asked because the newest release doesn't include client stuff, at least for the 0x12092000/ EP5 clients.

A side note:  It seems there is not a difference between pure EP5 clients and 0x12092000 clients, you can run both of them using the EP6 build and everything works as expected.

**Comment by kurtekat** [comment]
pretty much. the only difference is including SetItem.SData and using ps_game v2 or v3 to support 6 quest rewards, depending on what level cap you want. if i had a server, i'd likely use this configuration.

**Comment by Spelunkern** [comment]
Thanks for the help, im closing the issue ;)

**Comment by kurtekat** [comment]
no problem.

**Comment by kurtekat** [comment]
there's one mistake in the 6.0 build. i'm gonna take care of it now.

**Comment by kurtekat** [comment]
[6.0.zip](https://github.com/kurtekat/shaiya-episode-6/files/15084516/6.0.zip)

my bad. i didn't realize the synergy code wasn't in the build.

**Comment by kurtekat** [comment]
i'm gonna post a new release soon. i added client side support for this message:

```
509    "<t> killed  you <v> time(s)."
```
