### ISSUE TITLE
Hunter Class (Damage Delay)

### ISSUE THREAD

**Issue by Jabinnn** [kurtekat/shaiya-episode-6#91]
Good day!

I've found this delay damage when utilizing your most recent version, v1.4.6, on both the server and client side. Upon testing, only the auto attack or let's say the attack icon has the delay damage, and when I use a skill (any skill), it will fix. So I would say that only the Auto attack or normal attack has the bug. it appears that only the hunter class is affected by this bug.

Refer to the vid below

https://www.youtube.com/watch?v=XhCfFbFQEZY

**Comment by NatS0e** [comment]
Did you had this issue before, on lower versions? It seems like the well known bug of Ep6. Which also happen on Pets.dll servers.  Have seen a fix released in the community.

**Comment by Jabinnn** [comment]
Nah I only tested the latest, and yeah I'm trying to search for related issues in disc and elite but not succeeded.

**Comment by kurtekat** [comment]
it's client side. i had a fix for this somewhere. i'll see if i can find it.

**Comment by kurtekat** [comment]
```cpp
unsigned u0x593D73 = 0x593D73;
unsigned u0x593D1C = 0x593D1C;
void __declspec(naked) fn0x593D11()
{
    __asm
    {
        cmp al,0xB
        jne _0x593D73

        push 0x0

        // original
        movzx edx,byte ptr[esi+0x1FC]
        jmp u0x593D1C

        _0x593D73:
        jmp u0x593D73
    }
}

// fix javelin animation
util::detour((void*)0x593D11, fn0x593D11, 11);

// fix javelin animation
std::array<std::uint8_t, 2> a07{ 0x90, 0x90 };
std::array<std::uint8_t, 4> a10{ 0x8B, 0x54, 0x24, 0x3C };
std::array<std::uint8_t, 5> a11{ 0x0F, 0xB6, 0x4C, 0x24, 0x4C };
util::write_memory((void*)0x593D43, &a10, 4);
util::write_memory((void*)0x593D4F, &a07, 2);
util::write_memory((void*)0x593D49, &a11, 5);
```

**Comment by kurtekat** [comment]
it happens with an archer and a crossbow too. i'll look at it again and try to understand that workaround i posted a little better before i commit something to the repo.

**Comment by Jabinnn** [comment]
Thank you for the response sir! Great work as always.

**Comment by kurtekat** [comment]
no problem. that workaround hooked the 0x502 handler in the client, which makes sense. at the time i made it, i wasn't deep into packets. i just threw it together for an old friend.

**Comment by Jabinnn** [comment]
> it happens with an archer and a crossbow too. i'll look at it again and try to understand that workaround i posted a little better before i commit something to the repo.


Yeah, I've just realized something about the archer and the crossbow. Earlier, I didn't notice the delay in the archer and a crossbow while testing because I was more focused on the hunter's delay, which is more obvious. Unlike the archer, which shows damage right away with a slight delay, while the hunter requires another shot to display the damage. Anyway, thanks for sending the code—it sorted out the delay issue with the hunter! Thanks a lot!

**Comment by kurtekat** [comment]
i played an archer once, years ago with a crossbow, and it was really bad when my attack speed was maxed.

**Comment by kurtekat** [comment]
cool. no problem. i'm gonna close this as resolved.

**Comment by kurtekat** [comment]
i'm sure you noticed, when you hit a mob, the bug doesn't happen. i think i understand what's wrong. let's compare the working and non-working machine code.

## Mob (0x503 handler)

```
push 00
push 00
cmp al,0B
jne game.exe+1941E5
movzx edx,byte ptr [esi+000001FC]
movzx eax,word ptr [esi+000001F4]
movzx ecx,word ptr [esi+000001F2]
push edx
movzx edx,word ptr [esi+000001F0]
push eax
mov eax,[esi+000001EC]
push ecx
movzx ecx,byte ptr [esi+000001EA]
push edx
mov edx,[esp+44]
push eax
push ecx
movzx ecx,byte ptr [esp+54]
push edx
push 00
movzx eax,bl
push eax
push edi
push 00
push 00
push 00
push ecx
mov ecx,game.exe+3C4A68
call game.exe+5CBA0
```

## Character (0x502 handler)

```
push 00
cmp al,0B
jne game.exe+193D73
movzx edx,byte ptr [esi+000001FC]
movzx eax,byte ptr [esi+000001F4]
movzx ecx,word ptr [esi+000001F2]
push edx
movzx edx,word ptr [esi+000001F0]
push eax
movzx eax,word ptr [esi+000001EC]
push ecx
movzx ecx,byte ptr [esi+000001EA]
push edx
mov edx,[esp+38]
push eax
push ecx
movzx ecx,byte ptr [esp+48]
push edx
push 00
push 00
movzx eax,bl
push eax
push edi
push 00
push 00
push 00
push ecx
mov ecx,game.exe+3C4A68
call game.exe+5CBA0

```

see the difference? it looks like they passed the last 9 parameters in the wrong order. that `CWorldMgr` method takes 16 arguments, so it would have been an easy mistake.

so, i hope that explains the changes. i'll commit a cleaner version later.

**Comment by Jabinnn** [comment]
I'm seriously impressed by how you manage to find and test things. Your skills are incredible! It would take me ages to understand all of that on my own. Thankfully, your expertise and explanations make it much easier for beginners like me to grasp and distinguish between what's correct and what's not.

**Comment by kurtekat** [comment]
i appreciate the kind words. i also appreciate that you care about how things work.

i'll explain more, since you're showing an interest. the detour adds what should be the last parameter. one memory write removes the `push` that is misplaced. the other two memory writes increase the stack offsets by 4, because we added one `push` beforehand. otherwise, it would copy the wrong values. in this case, those values on the stack are more than likely variables that were declared inside the function. i hope that makes sense of everything.

ideally, i'd want to `typedef` that `CWorldMgr` method and fix this with real code, but for now, i'll just do it with assembly.

**Comment by Jabinnn** [comment]
Delving it more info from you makes me more fascinated. Right now, I'm really curious and checking myself in the game to understand how things operate, particularly with the machine code you provided earlier, and comparing it with my observations. 

Your insights and contributions are genuinely valued.

**Comment by kurtekat** [comment]
the `CCharacter` is in `esi`. i'm not sure if it's the target or the attacker. i don't have a definition for the member variables at those offsets either. i'll have to look at it sometime.

i can help you get started. i've attached a CT that will give you easy access to the character pointer in the world manager. with that find function, you can get anyone's client-side data if you know their character id.

https://github.com/kurtekat/shaiya-episode-6/blob/main/sdev-client/include/shaiya/include/CWorldMgr.h

i left a few things in there to give you an example. you can add more yourself, using this as a guide:

https://github.com/kurtekat/shaiya-episode-6/blob/main/sdev-client/include/shaiya/include/CCharacter.h

[CCharacter.zip](https://github.com/kurtekat/shaiya-episode-6/files/15258978/CCharacter.zip)

**Comment by Jabinnn** [comment]
Holyyy, it's like I've entered the dark web or something. Nonetheless, thank you for providing this, and yes, I'm definitely going to learn from it. Thank you so much, sir, your help is greatly appreciated.

**Comment by Jabinnn** [comment]
> Holyyy, it's like I've entered the dark web or something. Nonetheless, thank you for providing this, and yes, I'm definitely going to learn from it. Thank you so much, sir, your help is greatly appreciated.

After looking into it, I was surprised. The clue was already there – I mean, all the information is already in your repository. It just needs good guidance, and I'll say that's you.

**Comment by kurtekat** [comment]
you're welcome. good luck.
