### ISSUE TITLE
Remote professional attack defense tower damage reduced

### ISSUE THREAD

**Issue by gaobbcdd** [kurtekat/shaiya-episode-6#92]
Archers, mages, and other long-range attack professions have reduced damage to defense towers. When using melee weapons, the damage is normal

For example, archers use bows and arrows
Maximum damage 133, minimum damage 16
Archers use swords and knives
Minimum damage 355
videos
https://youtu.be/QntguEyqSU0

**Comment by kurtekat** [comment]
Check the Luc of those mobs. This happens with the Gold Pigs too, because their Luc is like 30k by default.

**Comment by Spotin2** [comment]
You may also check AttackTime3 column of that specific mob, since that's flagged as Range Defense in dbo.Mobs.

**Comment by gaobbcdd** [comment]
Thank you all. Detailed answers
