### ISSUE TITLE
Fix for Mantle/Badge Npc 

### ISSUE THREAD

**Issue by Spelunkern** [kurtekat/shaiya-episode-6#93]
I leave here the solution for a problem present on EP 5.4 ps_game, i think adding to the public .exe can be a good addition.
I lack the knowledge to apply the fix permanently on the executable :( 

Context of the issue:
EP 5.4 ps_game does not spawn Mantle merchants and badge merchants (Mantle customization npc) at server start, some vanilla Npc's. The visual issue regarding the edited mantles and dissapearing guild names (And other bugs) have been resolved, so i think fixing this feature it's wise.

[ENABLE]
//code from here to '[DISABLE]' will be used to enable the cheat
alloc(newmem,2048)
label(returnhere)
label(originalcode)
label(exit)

newmem: //this is allocated memory, you have read,write,execute access
//place your code here

originalcode:
jmp ps_game.exe+2FBD7
mov al,[ebx+00000124]

exit:
jmp returnhere

"ps_game.exe"+2FBBF:
jmp newmem
nop 3
returnhere:

[DISABLE]
//code from here till the end of the code will be used to disable the cheat
dealloc(newmem)
"ps_game.exe"+2FBBF:
db EB 16 8A 83 24 01 00 00

**Comment by kurtekat** [comment]
I'll provide the steps.

1. Open the file with OllyDbg (or drag and drop). Right-click the machine code and choose the following:

**Go to->Expression**

2. In the pop-up window, write `0042FBBF` in the text box and click **Ok**
3. Double click the instruction

```
JNZ SHORT 0042FBD7
```

4. Edit the instruction

```
JMP SHORT 0042FBD7
```

5. Check the **Fill with NOPs** box and click **Assemble**
6. Right-click the machine code and choose the following:

**Copy to executable->All modifications**

7. Click **copy all** when the pop-up window appears
8. Right-click the next pop-up window, click **Save file** and follow the prompts

**Comment by Spelunkern** [comment]
![Sin título](https://github.com/kurtekat/shaiya-episode-6/assets/150851205/b4a23fdc-5cd4-4ff0-bb84-e29eb4d2303f)
Working, thank you!
It's gonna be implemented on v9.1

Editing adresses in olly it's easy, my lack of knodledge lies when the scripts locate more memory to do the code, i don't know what to do with that.
This is the reason of why some features avaliable for months have never see the light on the project, not a way to implement them easily.

**Comment by kurtekat** [comment]
this kind of script doesn't need a memory allocation. it could have been written:

```
[ENABLE]
"ps_game.exe"+2FBBF:
jmp ps_game.exe+2FBD7

[DISABLE]
"ps_game.exe"+2FBBF:
jne ps_game.exe+2FBD7
```

**Comment by kurtekat** [comment]
the machine code there is checking if the npc is a merchant (1). then, it checks the type of merchant and doesn't allow type 7 and 8 to spawn. it's by design, just to be clear. makes sense, because they also block drops for capes from mobs.

**Comment by Spelunkern** [comment]
Brilliant as always.

I wonder if there is a way to implement scripts with memory allocation permanent to the exe; for what i know the only way it's transforming the assembly code to C++ and make a dll, but surely there is another way.

For a example **this small script:**
[ENABLE]
//code from here to '[DISABLE]' will be used to enable the cheat

// camlimit - game.exe ep 6
alloc(newmem,2048)
label(returnhere)
label(originalcode)
label(exit)

newmem: //this is allocated memory, you have read,write,execute access
//place your code here

//mov [game.exe+3484DC],(float)13

originalcode:
mov [game.exe+3484DC],(float)13 // change limit here
fld dword ptr [game.exe+3484DC]
jmp exit

exit:
jmp returnhere

"game.exe"+42BCD:
jmp newmem
nop
returnhere:

[DISABLE]
//code from here till the end of the code will be used to disable the cheat
dealloc(newmem)
"game.exe"+42BCD:
fld dword ptr [game.exe+3484DC]
//Alt: db D9 05 DC 84 74 00

Cups have explained months ago something about PE_Tools but i have never digged in the topic.

**Comment by kurtekat** [comment]
with this game we use, there's a lot of empty space for code caves. there's no need to create a new section :P

**Comment by Spelunkern** [comment]
So i basically look for an empty section and place the code?  Seems simple actually

**Comment by Spelunkern** [comment]
![Sin título](https://github.com/kurtekat/shaiya-episode-6/assets/150851205/c2b6f16c-42f0-4b8d-a04b-6ff09bdf5351)
Like this, where the main code ends and everything repeats for a while

**Comment by kurtekat** [comment]
sure. those sections that have been filled with null bytes have tons of room for mods. note: this may make a virus scan worse than it already is. i can't make recommendations from a picture. i'd have to look at it in PE tools and find the virtual addresses.

**Comment by kurtekat** [comment]
you have to be careful, because that could be memory used by legit game code that happens to be null when you're looking at it.

**Comment by kurtekat** [comment]
i'll go ahead and push the change to the repo. i modified them all while we were talking.

**Comment by Spelunkern** [comment]
I think converting to C++ seems more wise than edit the executable, which already gives some false positives.
Something like that:

#include <cstdint>
#include <cmath>

int main() {
    *reinterpret_cast<float*>(0x3484DC + reinterpret_cast<uintptr_t>(GetModuleHandle("game.exe"))) = 30.0f;
    float value = *reinterpret_cast<float*>(0x3484DC + reinterpret_cast<uintptr_t>(GetModuleHandle("game.exe")));
    goto exit;

exit:
    goto returnhere;

"game.exe"+42BCD:
    goto newmem;
    nop;
returnhere:
    return 0;
}

I don't know where to add that section anyways, but it's a start.
This script changes the max camera distance limit, by default 13.

**Comment by kurtekat** [comment]
with my library (see static.h) that could be greatly simplified

**Comment by kurtekat** [comment]
i think you could use my utility to write the value to that address.

**Comment by kurtekat** [comment]
try this. i will too.

```cpp
// camera limit
float camera_limit = 30.f;
util::write_memory((void*)0x7484DC, &camera_limit, 4);
```

**Comment by Spelunkern** [comment]
Where i locate that code specifically ?   (On static h)

**Comment by kurtekat** [comment]
> Where i locate that code specifically ? (On static h)

i misspoke. just use the memory write. it works :P

**Comment by kurtekat** [comment]
the static memory i defined is further out. it doesn't matter. if you need to write a value to an address, use the memory write like i just demonstrated. it's easier for someone else to read and doesn't do a bunch of silly shit.

**Comment by Spelunkern** [comment]
![Sin título](https://github.com/kurtekat/shaiya-episode-6/assets/150851205/60e9f59f-a5e8-4b21-91a1-1c032bb64fdb)
Sorry the noob questions, i mean where i place the new code section

**Comment by kurtekat** [comment]
you don't need to place anything anywhere. i said i **misspoke**.

**Comment by Spelunkern** [comment]
then my question it's how and where to use the memory write 😂

**Comment by kurtekat** [comment]
call it from any function. for example:

```cpp
void func()
{
    float camera_limit = 30.f;
    util::write_memory((void*)0x7484DC, &camera_limit, 4);
}
```

**Comment by Spelunkern** [comment]
Still a bit confused, i think it's normal for someone with zero previous knowledges in C++ and coding in general.

Nevermind, thanks for fixing the issue with the mantles and adding the fix to the repository!
You can add the camera distance feature to the project if you feel it wise.

About the same topic:

004BAFC8:
db 90 90 90 90 90 90 90 90 90

004BAFD1:
db 90 90 90 90 90 90 90 90 90

00473BBD:
db 90 90 90 90 90 90 90 90 90 90 90 90 90

This is the fix for mantles/helmets drop, already avaliable on essentials ps_game. In case you consider useful to add to the .exes.

Thank you again and sorry for bother with noob questions.

**Comment by kurtekat** [comment]
you're fine. i'm not qualified to teach other people. i have to learn as i go, just like everyone else. i recommend buying a beginner's course on Udemy. you might be able to find one for free on YouTube.

people can add the drop script on their own. npcs not spawning is an exception i'm willing to make, but only because of the circumstances.
