### ISSUE TITLE
Evolution and Potential Motive (Aka spell cooldown) Issues

### ISSUE THREAD

**Issue by Spelunkern** [kurtekat/shaiya-episode-6#96]
This have been present in almost all EP6 game.exes since the beggining, and i think it could be a good change to fix the problems with that skill types.

Skill Type: 90  ,  Evolution/Transformation/etc
When you use Evolution, after a second the effect gets visually bugged and the mob you have transformed on starts to walk/attack, the animations and final damage calculation bugs and ends ruining the skill concept.
This bug have never been present in EP 5.4 game.exe or even the build [0x12092000].

A relevant detail it's if you change map, use move or just reset your position, once you appear on the next location the effect works as expected and the animation/damage it's applied correctly.
This is a kind of bug like the mount ones when you change maps or TP, but in a reverse situation.

Ability Type:  Spell Cooldown Time   (It doesn't matter if it's a potential motive ability or a buff that gives that stat)
Again this bug starts on EP6 game.exe.
The problem lies about 3 things:
- It doesn't matter what number of cooldown reduction you have on the server side, the client always let you have 500s of cooldown reduction just if you have the stat or potential motive effect.
- You can use spells already charging.
- The proper 'Skill reduction' it's not applied visually;  for a example if you have 200s cooldown reduction and a spell with 210s recharge, the recharge interface it's gonna show the skill recharged in 10s, as long as the effect last.
This things have always worked on EP 5.4 game.exe and older versions and the issue have never been fixed.

It's a very old issue and i don't think it have terrible consequences, but i could be good to eventually take a look to see if something can be doed.
![Sin título](https://github.com/kurtekat/shaiya-episode-6/assets/150851205/a3c8cfd4-cbb9-4f45-a403-61061f91f995)

**Comment by kurtekat** [comment]
i doubt i'll be able to fix the buggy animations, but i know what you're talking about. i'll have to come back and read this again in the future. i can't wrap my peanut around it all at the moment.

**Comment by kurtekat** [comment]
> The problem lies about 3 things:
> 
> * It doesn't matter what number of cooldown reduction you have on the server side, the client always let you have 500s of cooldown reduction just if you have the stat or potential motive effect.
> * You can use spells already charging.
> * The proper 'Skill reduction' it's not applied visually;  for a example if you have 200s cooldown reduction and a spell with 210s recharge, the recharge interface it's gonna show the skill recharged in 10s, as long as the effect last.
>   This things have always worked on EP 5.4 game.exe and older versions and the issue have never been fixed.

Can you tell me what is expected?

**Comment by Spelunkern** [comment]
Correct behaviour (Up to 5.4 clients and EP6 OS)
- Cooldown reduction matches the value you use in the client/server. (Bugged one always takes 500s)
- Spells charging can't be used if you have cooldown reduction active.
- Spells recharge faster according to the current cooldown reduction you have active.

**Comment by kurtekat** [comment]
Thank you. That helps a lot.

**Comment by Spelunkern** [comment]
Thank to you for looking on this topic; if you need any other info or test just tell me.

**Comment by Spelunkern** [comment]
An additional info on the Evolution issue:

There is not a problem with the animation or effect itself, the problem it's the client mess up the effect after a brief moment. The best example it's the bug ends when you change maps.
The fix to that issue could be forcing the client to send the correct packet at the right time, but it doesn't need further modifications.

**Comment by kurtekat** [comment]
I've got a test fix for the evolution issues. Ping me when you're available.

**Comment by kurtekat** [comment]
https://github.com/Spelunkern/Shaiya-Essentials/commit/4860b0ce8d1448fa8715101201d327dd7015127a

The evolution issue is related to pets being added to the game. Please test the patch. It looks ok to me. This is is all I can do about it, so I hope it works out :P

**Comment by kurtekat** [comment]
As far as the potential motive issue is concerned, this is what I've observed:

```
game.exe+1B3183  mov cx,[game.exe+1EAACF4] { (0) }
game.exe+1B318A  cmp [edx+38],cx
game.exe+1B318E  ja game.exe+1B31AA
```

When potential motive is activated, 500 is written to `022AACF4` and compare to the `resetTime` of the skill. It doesn't evaluate whether the skill is in cooldown. It just allows it to cast if the `resetTime` is less than 500. I think it's intentional, regardless of whether ep5 behaved the same way.

If it's all the same to you, I'd like to leave this alone.  I'm a little tired of chasing ghosts. I'll update the `SkillInfo` structure for those that want to study this further.

**Comment by Spelunkern** [comment]
Hey, im gonna test when i get back to work, thank you

**Comment by Spelunkern** [comment]
Working fine, nice to finally see again an use for that skill type.
I see you have also increased the camera distance, thanks for that, highly
appreciated.

**Comment by kurtekat** [comment]
You're welcome.
