### ISSUE TITLE
OS : CT2 (Dimension Crack) Enter with Dragon Buff inside of portal.

### ISSUE THREAD

**Issue by xareI** [kurtekat/shaiya-episode-6#97]
I remember CT2 portal opening with a buff and when buff is disappeear / time expired.
Automatic teleport to kanos again.
I did test with like OS style but doesn't work, if library gonna support "buffs log in w/ portals" gonna be great.

For better undestand here is reference video : 
[https://youtu.be/YzVNWPN-3e8?si=aajsDovkFyK3fBs_&t=672](url)

**Comment by kurtekat** [comment]
I don't want to get into this feature.

**Comment by kurtekat** [comment]
I'm not interested in working on this feature.

**Comment by kurtekat** [comment]
https://github.com/kurtekat/shaiya-episode-6/blob/c18991b1b9337617baefa75784ad03d21ba019e5/shaiya/include/skill/SkillAbilityType.h#L57

https://github.com/kurtekat/shaiya-episode-6/blob/c18991b1b9337617baefa75784ad03d21ba019e5/sdev/include/shaiya/src/Helpers.cpp#L130
