### ISSUE TITLE
Quick casting bar (R) Issue

### ISSUE THREAD

**Issue by Spelunkern** [kurtekat/shaiya-episode-6#98]
I have discovered this bug while testing, it seems it's present in only recent versions.

I can confirm the quick casting bar it's a client issue, since using a clean game.exe removes the issue.
The problem lies about the skills displaying in an incorrent position in the upper part of the interface, where you asign the quick casting chain.

It seems something it's intervening with that interface position.
![Sin título](https://github.com/kurtekat/shaiya-episode-6/assets/150851205/7523cad0-7959-45c9-9802-c1e4538cbdcf)

**Comment by kurtekat** [comment]
I don't think I should get into these things, unless my coding caused the problem.

**Comment by kurtekat** [comment]
the code in this repo is fine. the essential code has the bug. why did you open the issue here?

anyhow, i know what it is, so i'll take care of it.

**Comment by kurtekat** [comment]
the bug is in the essentials code. i'll take care of it.

**Comment by kurtekat** [comment]
done. changing the value of the float number at that address to change the camera limit was the cause. static floats and doubles are typically used at several places. in this case, the revolver icon positions. i set a detour instead.

that's what i get for trusting a snip from another source. i should have used my own code in the first place. next time, please open the issue in the essentials repository or email me. this project isn't the same :P

**Comment by kurtekat** [comment]
actually, i'm going to leave the repository. i just wanted to get it started. good luck.

**Comment by Spelunkern** [comment]
I incorrectly supposed both repositories have the bug; was my mistake to
open the issue on the ep6 one.
Thank you for the fix!
Currently i don't have any short-term plans to update or expand the client
dll besides small changes.

**Comment by kurtekat** [comment]
no need to apologize. understood.

**Comment by kurtekat** [comment]
understood. i hope people that use it will help out when you need a hand.
